---
sidebar: sidebar
permalink: application.html
keywords:
summary:
---

= Application
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-10 15:58:00.715535
//

[.lead]
You can use these API calls to manage the ONTAP application resources.

==== Applications

The ONTAP applications are arranged based on type, including: templates, applications,  components, and Snapshot copies. This resource type was introduced with ONTAP 9.6.

==== Application snapshots

Applications support snapshot copies, which can be created or restored at any time. This resource type was introduced with ONTAP 9.6.

==== Consistency groups

A consistency group is a set of volumes that are grouped together when performing certain operations such as a snapshot. This feature extends the same crash consistency and data integrity implicit with single-volume operations across a set of volumes. This resource type was introduced with ONTAP 9.10.

==== Consistency groups snapshots

You can use these endpoints to copy, create, inventory, and restore SnapShots for a consistency group. This resource type was introduced with ONTAP 9.10.
