---
sidebar: sidebar
permalink: get_more_information.html
keywords:
summary:
---

= Get more information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-10 15:58:00.644064
//

[.lead]
There are several additional resources you can access to get help and find more information about how to automate the deployment and administration of your ONTAP storage systems.

=== ONTAP 9 resources

// https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center^]
* https://docs.netapp.com/us-en/ontap/[ONTAP 9 Documentation^]
+
Provides all of the documentation for ONTAP 9.

* https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx[ONTAP and ONTAP System Manager Resources^]
+
Provides documentation and other helpful links needed to plan, administer, and support ONTAP 9.

=== ONTAP 9 developer resources

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2876895[ONTAPI to REST API mapping information^]
+
Provides the key ONTAPI calls and the mapping to the equivalent REST API calls.

* https://devnet.netapp.com/restapi.php[NetApp Developer Network: ONTAP RESTful API^]
+
Provides resources and documentation needed to use the ONTAP REST API, including the ONTAP Python client library.

=== Videos

* https://www.youtube.com/watch?v=Wws3SB5d9Ss[Getting started with the NetApp ONTAP Python client library^]
+
Good introduction to the NetApp Python client library and how to get started writing code using the library.

=== NetApp resources

* https://mysupport.netapp.com/[NetApp Support^]
+
Access troubleshooting tools, documentation, and technical support assistance.

* https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
+
Access requirements and compatibility information related to using ONTAP 9 and the ONTAP REST API.

* http://www.netapp.com/us/library/index.aspx[NetApp library of technical reports and white papers^]
+
Access technical reports, white papers, and other documents.
