---
sidebar: sidebar
permalink: ndmp.html
keywords:
summary:
---

= NDMP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-10 15:58:00.845173
//

[.lead]
The Network Data Management Protocol provides a standard for backing up NAS devices. You can use these API calls to manage the NDMP services.

==== NDMP mode

The NDMP operational mode can be SVM scope or node scope. This resource type was introduced with ONTAP 9.7.

==== NDMP nodes

You can manage the NDMP configuration of the nodes. This resource type was introduced with ONTAP 9.7.

==== NDMP sessions

You can retrieve and delete NDMP session details for a specific SVM or node. This resource type was introduced with ONTAP 9.7.

==== NDMP SVMs

You can manage the NDMP configuration of the SVMs. This resource type was introduced with ONTAP 9.7.

==== NDMP SVM user passwords

You can generate and retrieve passwords for a specific NDMP user within the SVM content. This resource type is new with ONTAP 9.8.


