---
sidebar: sidebar
permalink: new_ontap_automation.html
keywords: new features
summary: There are several new and changed automation features with the current release of ONTAP.
---

= What's new with ONTAP 9.9.1 automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several new and changed automation features provided with the current ONTAP release.

=== ONTAP 9.9.1 REST API

ONTAP 9.9.1 continues to expand the capabilities of the ONTAP REST API. There are new API endpoints for existing ONTAP features, including SAN port sets and SVM file directory security. In addition, endpoints have been added to support new ONTAP 9.9.1 features and enhancements. And the related documentation has also been improved. A summary of the enhancements is presented below.

Mapping ONTAPI to the ONTAP 9 REST API::

To help you transition your ONTAP automation code to the REST API, NetApp provides API mapping documentation. This reference includes a list of ONTAPI calls and the REST API equivalent for each. The mapping document has been updated to include the new ONTAP 9.9.1 API end points. See https://library.netapp.com/ecm/ecm_download_file/ECMLP2876895[ONTAPI to REST API mapping information^] for more information.

API endpoints for new ONTAP 9.9.1 core features::

Support for new ONTAP 9.9.1 features that are not available through the ONTAPI API has been added to the REST API. This includes support for nested igroups and Google Cloud Key Management Services.

Improved support for transitioning to REST from ONTAPI::

More of the legacy ONTAPI calls now have corresponding REST API equivalents. This includes local Unix users and groups, management of NTFS file security without the need for a client, SAN port sets, and volume space attributes. These changes are also included in the updated ONTAPI to REST mapping documentation.

Enhanced online documentation::

The ONTAP online documentation reference page now includes labels indicating the ONTAP release when each REST endpoint or parameter was introduced, including those new with ONTAP 9.9.1.
