---
sidebar: sidebar
permalink: new_ontap_automation.html
keywords: new features
summary: There are several new and changed automation features with the current release of ONTAP.
---

= What's new with ONTAP 9.10.1 automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several new and changed automation features provided with the current ONTAP release.

=== ONTAP 9.10.1 REST API

ONTAP 9.10.1 continues to expand the capabilities of the ONTAP REST API. Over a hundred new endpoints have been added to support new ONTAP features as well as enhancements to existing features. A summary of the REST API enhancements is presented below.

Application consistency group::

A consistency group is a set of volumes that are grouped together when performing certain operations such as a snapshot. This feature extends the same crash consistency and data integrity implicit with single-volume operations across a set of volumes. It is valuable for large multi-volume workload applications.

SVM migration::

You can migrate an SVM from a source cluster to a destination cluster. The new endpoints provide complete control, including the ability to pause, resume, retrieve status, and abort a migration operation.

File cloning and management::

Volume-level file cloning and management have been enhanced. New REST endpoints support file move, copy, and split operations.

Improved S3 auditing::

Auditing of the S3 events is a security improvement allowing you to track and log certain S3 events. An S3 audit event selector can be set on a per SVM per bucket basis.

Ransomware defense::

ONTAP detects files potentially containing a ransomware threat. You can retrieve a list of these suspect files as well as remove them from a volume.

Miscellaneous security enhancements::

There are several general security enhancements that expand existing protocols and introduce new capabilities. Improvements have been made to IPSEC, key management, SSH configuration, and file permissions.

CIFS domains and local groups::

Support for CIFS domains has been added at the cluster and SVM level. You can retrieve the domain configuration as well as create and remove preferred domain controllers.

Expanded volume analytics::

Volume analytics and metrics have been expanded through additional endpoints to support top files, directories, and users.

Support enhancements::

Support has been enhanced through several new features. Automatic update can keep your ONTAP systems current by downloading and applying the latest software updates. You can also retrieve and manage the memory core dumps generated by a node.
