---
sidebar: sidebar
permalink: options_for_ontap_automation.html
keywords: ontap, ontap automation, rest, ontap rest api, python client library, ontap ansible
summary: There are several options for automating the deployment and administration of ONTAP storage systems.
---

= Options for ONTAP automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-10 15:58:00.644064
//

[.lead]
Beginning with ONTAP 9.6, ONTAP includes an expansive REST API that provides the foundation for automating the deployment and administration of your storage systems. You can access the REST API directly or through the NetApp Python client library. In addition, NetApp supports ONTAP automation using Ansible as well as other high-level software abstractions.

=== Accessing the ONTAP REST API natively

You can access the ONTAP REST API directly using any programming language that supports a REST client. Popular language choices include Python, PowerShell, and Java. You should begin by reviewing the documentation at this site, including link:getting_started_with_the_rest_api.html[Getting started with the REST API].

=== Adapt legacy ONTAPI code to use REST

If you have existing code using the ONTAPI API, NetApp provides support for converting your code to use the newer ONTAP REST API. See https://library.netapp.com/ecm/ecm_download_file/ECMLP2876895[ONTAPI to REST API mapping information^] for information about mapping the ONTAPI calls to the equivalent REST API calls.

=== Using the NetApp Python client library

The Python client library is a package you can use when writing scripts to access the ONTAP REST API. It provides support for several underlying services, including connection management, asynchronous request processing, and exception handling. By using the Python client library, you can quickly develop robust code to support your ONTAP automation goals. You should begin by reviewing the documentation at this site, including link:accessing_the_rest_api_using_python.html[Accessing the REST API using Python].

=== Using Ansible

Ansible is an open-source software tool that supports provisioning, configuration management, and application deployment. Since its release and subsequent acquisition by RedHat, it has continued to grow in popularity. NetApp provides Ansible-certified modules that customers can use to automate the administration of their ONTAP storage systems. You should begin by reviewing the documentation at this site, including link:ontap_ansible.html[ONTAP and Ansible automation].
