---
sidebar: sidebar
permalink: preparing_to_use_the_python_client_library.html
keywords:
summary:
---

= Preparing to use the Python client library
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-09 14:53:22.811594
//

[.lead]
You should prepare the environment before using the Python client library.

=== Basic requirements

You must use Python 3.5 or later. In addition, the following packages are also required:

* requests 2.22.1 or later
* requests-toolbelt 0.9.1 or later
* marshmallow 3.2.1 or later

=== Package name and version

The name of the Python client library package is *netapp_ontap*. The version associated with the package is a combination of the ONTAP major and minor version numbers the library was generated from, along with a minor version for the client within the ONTAP release. For example,  valid version numbers include: 9.6.1, 9.6.2, and 9.7.1.

=== Installation

You must use pip to install the netapp_ontap package from the Python Package Index (PyPi) web site.

=== Documentation and additional resources

See the _NetApp Developer Network_ for links to documentation and other resources. There is also a GitHub repository containing code samples and other helpful information.

.Related links

https://devnet.netapp.com/restapi[NetApp Developer Network: ONTAP RESTful API^]

https://github.com/NetApp/ontap-rest-python[ONTAP REST Python GitHub repository^]
