---
sidebar: sidebar
permalink: preparing_to_use_the_workflow_processes.html
keywords:
summary:
---

= Preparing to use the workflow processes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-09 12:46:18.707587
//

[.lead]
You should prepare before using the workflow processes.

=== Understanding the API calls used in the workflows

The ONTAP API online documentation page includes the details of every REST API call. Rather than repeat those details here, each API call used in the workflow samples includes only the information you need to locate the call on the documentation page. After locating a specific API call, you can review the complete details of the call, including the input parameters, output formats, HTTP status codes, and request processing type.

The following information is included for each API call within a workflow to help locate the call on the documentation page:

* Category
+
The API calls are organized on the documentation page into functionally related areas or categories. To locate a specific API call, scroll to the bottom of the page and click the applicable API category.

* HTTP method
+
The HTTP method identifies the action performed on a resource. Each API call is executed through a single HTTP method.

* Path
+
The path determines the specific resource which the action applies to as part of performing a call. The path string is appended to the core URL to form the complete URL identifying the resource.

=== Constructing a URL to directly access the REST API

In addition to the ONTAP documentation page, you can also access the ONTAP REST API directly through a programming language such as Python. In this case, the core URL is slightly different than the URL used when accessing the online documentation page. When accessing the API directly, you must append /api to the domain and port string. For example: `https://ontap.mycompany.com/api`

.Related links

<<how-access-api>>

ADD LINK
