---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP Automation docs
      url: /index.html
    - section: rn
    - section: get-started
    - section: rest
    - section: workflows
    - section: python
    - section: automate
    - section: reference
    - section: additional
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: ONTAP automation options
          url: /intro/options_for_ontap_automation.html
        - title: Before you begin
          url: /get-started/get_started_before.html
        - title: Retrieve cluster software version
          url: /get-started/retrieve_cluster_software_version.html
        - title: Hello world
          url: /get-started/hello_world.html
