---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP Automation docs
      url: /index.html
    - section: rn
    - section: get-started
    - section: rest
    - section: workflows
    - section: manage
    - section: python
    - section: reference
    - section: automate
    - section: migrate
    - section: additional
    - title: Legal notices
      url: /legal-notices.html

product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: All ONTAP product documentation

homepage:
  tiles:
    - title: Get started
      links:
        - title: Release Notes
          url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
        - title: ONTAP automation options
          url: /get-started/ontap_automation_options.html
        - title: Your first API call
          url: /get-started/first_call.html
    - title: ONTAP REST API
      links:
        - title: REST implementation details
          url: /rest/rest_web_services_foundation.html
        - title: Additional considerations
          url: /rest/object_references_and_access.html
        - title: Summary of REST resources
          url: /resources/overview_categories.html
        - title: API reference
          url: /reference/api_reference.html
    - title: Automation
      links:
        - title: Python client library
          url: /python/overview_pcl.html
        - title: ONTAP and Ansible
          url: /automate/ontap_ansible.html
        - title: Automation blogs
          url: /automate/blogs.html
    - title: Migrate to the REST API
      links:
        - title: ONTAPI disablement
          url: /migrate/overview.html
        - title: ONTAPI to REST mapping
          url: /migrate/mapping.html
        - title: Performance counters
          url: /migrate/performance-counters.html
        - title: Blog articles
          url: /migrate/blogs.html
    - title: More resources
      links:
        - title: Get more information
          url: /additional/get_more_information.html
        - title: NetApp DevNet
          url: https://devnet.netapp.com/restapi.php
        - title: ONTAP 9 docs
          url: https://docs.netapp.com/us-en/ontap/
        - title: ONTAP Select docs
          url: https://docs.netapp.com/us-en/ontap-select/
