---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP Automation docs
      url: /index.html
    - section: intro

homepage:
  tiles:
