settings:
  name: ONTAP automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP automation docs
      url: /index.html
    - title: What's new
      entries:
        - title: What's new with the ONTAP REST API
          url: /whats-new.html
        - title: Changes to ONTAP REST API calls
          url: /api-changes.html
    - section: get-started
    - section: rest
    - section: workflows
    - section: sw-tools
    - section: migrate
    - section: reference
    - section: additional
    - title: Legal notices
      url: /legal-notices.html

product-family: 
  name: ONTAP
  repo: ontap-family