---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP Automation docs
      url: /index.html
    - section: rn
    - section: get-started
    - section: rest
    - section: workflows
    - section: python
    - section: automate
    - section: reference
    - section: additional
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: ONTAP automation options
          url: /get-started/ontap_automation_options.html
        - title: Prepare to use the REST API
          url: /get-started/prepare.html
        - title: Retrieve cluster software version
          url: /get-started/retrieve_cluster_software_version.html
        - title: Hello world
          url: /get-started/hello_world.html
    - title: ONTAP REST API
      links:
        - title: REST implementation details
          url: /rest/rest_web_services_foundation.html
        - title: Additional REST considerations
          url: /rest/object_references_and_access.html
        - title: Summary of the resource categories
          url: /resources/overview_categories.html
