settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP Automation docs
      url: /index.html
    - title: What's new
      url: /whats-new.html
    - section: get-started
    - section: rest
    - section: workflows
    - section: sw-tools
    - section: migrate
    - section: reference
    - section: additional
    - title: Legal notices
      url: /legal-notices.html