---
sidebar: sidebar
permalink: storage.html
keywords:
summary:
---

= Storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-10 15:58:01.030867
//

[.lead]
You can use these API calls to manage the physical and logical storage.

==== Aggregates

An aggregate consists of one or more RAID groups. This resource type was introduced with ONTAP 9.6.

==== Aggregate plexes

A physical copy of the WAFL storage within an aggregate. This resource type was introduced with ONTAP 9.6.

==== Aggregate metrics

You can retrieve historical metrics data for a specific aggregate. This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.7.

==== Bridges

You can retrieve the bridges in a cluster. This resource type was introduced with ONTAP 9.9.

// 9.9

==== Disks

The physical disks in the cluster. This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.7 and 9.8.

==== FlexCaches

The persistent cache of an origin volume. This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.8.

==== FlexCache origins

FlexCache is a persistent cache of an origin volume. This resource type was originally introduced with ONTAP 9.6. Support has been enhanced with ONTAP 9.9 to support modification through the HTTP PATCH method.

// 9.9

==== Monitored files

You can designate specific files for additional monitoring. This resource type is new with ONTAP 9.8.

==== Ports

Storage ports of the cluster. This resource type was introduced with ONTAP 9.6.

==== QOS policies

Quality of service policy configuration. This resource type was introduced with ONTAP 9.6.

==== Qtrees

You can use these API calls to management Qtrees, a type of logically divided file system. This resource type was introduced with ONTAP 9.6.

==== Quota reports

Report on quotas, which is a technique for restricting or tracking files or space usage. This resource type was introduced with ONTAP 9.6.

==== Quota rules

The rules used to enforce the quotas. This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.7.

==== Shelves

Shelves in the cluster. This resource type was introduced with ONTAP 9.6.

==== Snapshot policies

Snapshots are created based on policies. This resource type was introduced with ONTAP 9.6.

==== Snapshot schedules

You can control the snapshot schedules. This resource type is newly redesigned with ONTAP 9.8.

==== Switches

You can retrieve the switches in a cluster. This resource type was introduced with ONTAP 9.9.

==== Tape devices

You can retrieve the tape devices in a cluster. This resource type was introduced with ONTAP 9.9.

==== Volume efficiency policies

You can use these API calls to configure the efficiencies applied to an entire volume. This resource type is new with ONTAP 9.8.

==== Volumes

Logical containers are used to serve data to clients. This resource type was introduced with ONTAP 9.6.

*update 9.9.1*
>> more attributes
>> /storage/volumes  and then open GET and open model and click *space*

==== Volume files

You can retrieve a list of files and directories for a specific directory on a volume. This resource type was introduced with ONTAP 9.7 and updated with ONTAP 9.8.

==== Volumes Snapshots

Snapshots for a volume. This resource type was introduced with ONTAP 9.6.
