---
sidebar: sidebar
permalink: summary_of_the_rest_resource_categories.html
keywords:
summary:
---

= Summary of the REST resource categories
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-10 15:58:00.695900
//

[.lead]
The resources available through the ONTAP REST API are organized in categories, as displayed on the ONTAP API documentation page. A brief description of each of the resources with the base resource paths is presented below, along with additional usage considerations where appropriate.

This section describes the REST resources for the latest version of the product. If you need to understand the changes that were made from the previous version, see the `Release Notes`.

[IMPORTANT]
For many of the REST endpoints, you can include a UUID key as part of the path string to access a specific object instance. However, you can also access objects using a property value on a query parameter.

.Related links

link:additional_considerations_when_using_the_rest_api.html[Additional considerations when using the REST API]

link:accessing_the_ontap_api_documentation_page.html[Accessing the ONTAP API documentation page]
