---
sidebar: sidebar
permalink: resources/object_store.html
keywords: object store resources
summary: You can use these API calls to access S3-based object storage.
---

= Object store
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use these API calls to access S3-based object storage.

.Buckets

A bucket is a container of objects and is structured using an object name space. Each S3 object server can have multiple buckets. This resource type was introduced with ONTAP 9.7 and updated with ONTAP 9.8.

.Services

You can create and manage the ONTAP S3 configuration, including servers and bucket configurations. This resource type was introduced with ONTAP 9.7.

.Service buckets

A bucket is a container of objects and is structured using an object name space. You can manage the buckets for a specific S3 server. This resource type was introduced with ONTAP 9.7.

.S3 bucket rules

The S3 buckets can include a rule definition. Each rule is a list objects and defines the set of actions to be performed on an object within the bucket. This resource type was introduced with ONTAP 9.13.

.S3 groups

You can create groups of S3 users and manage access control at the group level. This resource type is new with ONTAP 9.8.

.S3 policies

You can create an S3 policy and associate it with a resource to define various permissions. This resource type is new with ONTAP 9.8.

.Users

The S3 user accounts are maintained at the S3 server. User accounts are based on a pair of keys and associated with the buckets they control. This resource type was introduced with ONTAP 9.7.
