---
sidebar: sidebar
permalink: resources/overview_categories.html
keywords: resources, resource categories
summary: The resources available through the ONTAP REST API are organized in categories. Each of the resource categories includes a brief description along with additional usage considerations where appropriate.
---

= Overview of the resource categories in the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The resources available through the ONTAP REST API are organized in categories. Each of the resource categories includes a brief description along with additional usage considerations where appropriate.

The REST resources described in the summary are based on the latest version of the product. If you need a more detailed understanding of the changes made in previous releases, see link:../whats-new.html[What's new with the ONTAP REST API] as well as the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^].

[TIP]
For many of the REST endpoints, you can include a UUID key as part of the path string to access a specific object instance. However, in many cases you can also access objects using a property value on a query parameter.

.Related information

* link:../reference/api_reference.html[API reference]
