---
sidebar: sidebar
permalink: resources/security.html
keywords: rest, rest api, security, security resources
summary: You can use these API calls to manage the security settings for the cluster and SVMs.
---

= Security resources in the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use these API calls to manage the security settings for the cluster and SVMs.

.Accounts

There is a collection of user accounts for the cluster and SVMs. This resource type was introduced with ONTAP 9.6.

.Accounts name

The configuration for a scoped user account. This resource type was introduced with ONTAP 9.6.

.Active Directory proxy

You can administer the SVM account information at the Active Directory server. This resource type was introduced with ONTAP 9.7.

.Anti-ransomware

ONTAP detects files potentially containing a ransomware threat. There are several categories of endpoints. You can retrieve a list of these suspect files as well as remove them from a volume. This resource type was introduced with ONTAP 9.10.1. Support for displaying the version and updating the anti-ransomware package was added with ONTAP 9.16.

.Anti-ransomware enablement

You can control the operation of the Autonomous Ransomware Protection (ARP) enablement feature. This includes retrieving and modifying the configuration settings. This resource type was introduced with ONTAP 9.18.1.

.Anti-ransomware entropy stats

Detailed entropy statistics are available for the operation of the Autonomous Ransomware Protection (ARP) feature. This resource type was added with ONTAP 9.17.1.

.Audit

The settings which determine what is logged to the audit log files. This resource type was introduced with ONTAP 9.6.

.Audit destinations

These settings control how audit log information is forwarded to remote systems or splunk servers.  This resource type was introduced with ONTAP 9.6.

.Audit messages

You can retrieve the audit log messages. This resource type was introduced with ONTAP 9.6.

.AWS KMS

Amazon Web Services includes a key management service that provides secure storage for keys and other secrets. You can access this service through the REST API to allow ONTAP to securely store its encryption keys in the cloud. In addition, you can create and list the authentication keys used with NetApp Storage Encryption. This support is new with ONTAP 9.12.

.Azure Key Vault

This set of API calls allows you to use the Azure Key Vault to store the ONTAP encryption keys. This resource type is new with ONTAP 9.8.

.Barbican KMS

Support for the OpenStack Barbican key manager has been added to maintain keys for NetApp Volume Encryption (NVE). This resource type was added with ONTAP 9.17.1.

.Certificates

The APIs calls can be used to install, display, and delete certificates used by ONTAP. This resource type was introduced with ONTAP 9.7.

.Cisco Duo

Duo provides two-factor authentication for SSH logins. You can configure Duo to operate at the ONTAP cluster or SVM level. This resource type was introduced with ONTAP 9.14.

.Cluster network security

You can retrieve and update the cluster network security configuration including the certificates. This resource type was introduced with ONTAP 9.18.

.Cluster security

You can retrieve details of the cluster-wide security and update certain parameters. This resource type was introduced with ONTAP 9.7 and updated with ONTAP 9.8.

.External roles

An external role is defined at an OAUTH 2.0 identify provider. You can create and administer mapping relationships between these external roles and the ONTAP roles. This resource type was introduced with ONTAP 9.16.

.GCP KMS

This set of API calls allows you to use the Google Cloud Platform Key Management Service to store and manage the ONTAP encryption keys. This resource type was initially introduced with the ONTAP 9.8 REST API. However, this feature has been redesigned and so is considered to be new, with new resources types, in ONTAP 9.9.

.Groups

You can administer group configurations including groups represented with UUIDs. This resource type was introduced with ONTAP 9.16.

.Group role mappings

You can create and administer mapping relationships between groups and roles. This resource type was introduced with ONTAP 9.16.

.HA network security

You can retrieve and update the HA network security configuration. This resource type was introduced with ONTAP 9.18.


.IPSec

Internet Protocol Security (IPSec) is a suite of protocols providing security between two endpoints over an underlying IP network. This resource type is new with ONTAP 9.8.

.IPSec CA certificates

You can add, remove, and retrieve IPSec CA certificates. This resource type is new with ONTAP 9.10.

.IPSec policies

You can use this set of API calls to manage the policies in effect for an IPSec deployment. This resource type is new with ONTAP 9.8.

.IPSec security associations

You can use this set of API calls to manage the security associations in effect for an IPSec deployment. This resource type is new with ONTAP 9.8.

.Just in time (JIT) privilege elevation

(JIT) privilege elevation is an enhancement to role-based access control (RBAC). Cluster administrators can request temporary elevation to an existing role. This resource type was added with ONTAP 9.17.1.

.Key manager configurations

These endpoints allow you to retrieve and update the configurations for key managers. This resource type is new with ONTAP 9.10.

.Key managers

A key manager allows client modules within ONTAP to securely stored keys. This resource type was introduced with ONTAP 9.6 and updated for ONTAP 9.7. There was another update with ONTAP 9.12 to support authentication keys. A restore capability was added with ONTAP 9.13.

.Key stores

A key store describes the type of a key manager. This resource type is new with ONTAP 9.10. Additional endpoints supporting enhanced control were added with ONTAP 9.14.

.LDAP authentication

These API calls are used to retrieve and manage the cluster LDAP server configuration. This resource type was introduced with ONTAP 9.6.

.Login messages

Used to display and manage the login messages used by ONTAP. This resource type was introduced with ONTAP 9.6.

.Multiple administrator verification

The multiple administrator verification feature provides a flexible authorization framework for protecting access to ONTAP commands or operations. There are seventeen new endpoints that support defining, requesting, and approving access in the following areas:

* Rules
* Requests
* Approval groups

Providing the option for multiple administrators to approve access improves the security of your ONTAP and IT environments. These resource types were introduced with ONTAP 9.11.

.NIS authentication

These settings are used to retrieve and manage the cluster NIS server configuration. This resource type was introduced with ONTAP 9.6.

.OAuth 2.0

Open Authorization (OAuth 2.0) is a token-based framework that can be used to restrict access to your ONTAP storage resources. You can use it with clients that access ONTAP through the REST API. This resource type was introduced with ONTAP 9.14. It was enhanced with ONTAP 9.16 through the support of the Microsoft Entra ID authorization server (formerly Azure AD) with standard OAuth 2.0 claims. In addition, the Entra ID standard group claims based on UUID style values are supported through new group and role mapping capabilities. A new external role mapping feature has also been introduced. Also see *External roles*, *Groups*, and *Group role mappings*.

.Password authentication

This includes the API call used to change the password for a user account. This resource type was introduced with ONTAP 9.6.

.Privileges for a role instance

Manage the privileges for a specific role. This resource type was introduced with ONTAP 9.6.

.Public key authentication

You can use these API calls to configure the public keys for user accounts. This resource type was introduced with ONTAP 9.7.

.Roles

The roles provide a way to assign privileges to user accounts. This resource type was introduced with ONTAP 9.6.

.Roles instance

Specific instance of a role. This resource type was introduced with ONTAP 9.6.

.SAML service provider

You can display and manage the configuration for the SAML service provider. This resource type was introduced with ONTAP 9.6.

.SAML service provider default metadata

You can manage the SAML default metadata configuration for a cluster. This resource type was added with ONTAP 9.17.1.

.SSH

These calls allow you to set the SSH configuration. This resource type was introduced with ONTAP 9.7.

.SSH SVMs

These endpoints allow you to retrieve the SSH security configuration for all SVMs. This resource type was introduced with ONTAP 9.10.

.TOTPS

You can use the REST API to configure time-based one-time password (TOTP) profiles for accounts that sign in and access ONTAP using SSH. This resource type was introduced with ONTAP 9.13.

.Web authentication

Web authentication (WebAuthn) is a web standard for securely authenticating users based on public key cryptography. With ONTAP, it supports the administration of phishing-resistent MFAs through System Manager and the ONTAP REST API. This feature was added with ONTAP 9.16.