---
sidebar: sidebar
permalink: resources/storage.html
keywords: storage resources
summary: You can use these API calls to manage the physical and logical storage.
---

= Storage resources in the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use these API calls to manage the physical and logical storage.

.Aggregate metrics

You can retrieve historical metrics data for a specific aggregate. This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.7.

.Aggregate plexes

A physical copy of the WAFL storage within an aggregate. This resource type was introduced with ONTAP 9.6.

.Aggregates

An aggregate consists of one or more RAID groups. This resource type was introduced with ONTAP 9.6.

.Bridges

You can retrieve the bridges in a cluster. This resource type was introduced with ONTAP 9.9.

.Disks

The physical disks in the cluster. This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.7 and 9.8.

.File clone

You can use these endpoints to create file clones, retrieve split status, and manage split loads. The file cloning endpoint resources were first introduced with ONTAP 9.6 and expanded with ONTAP 9.8. They were significantly expanded again with ONTAP 9.10.

.File moves

You can use these REST API endpoints to move a file between two FlexVol volumes or within a FlexGroup volume. After the request is accepted you can monitor the progress and status. This resource type was introduced with ONTAP 9.11.1.

.FlexCache

This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.8.

.FlexCache origins

FlexCache is a persistent cache of an origin volume. This resource type was originally introduced with ONTAP 9.6. Support has been enhanced with the ONTAP 9.9 REST API to support modification through the HTTP PATCH method.

.Monitored files

You can designate specific files for additional monitoring. This resource type is new with ONTAP 9.8.

.Pools

You can create a shared storage pool as well as retrieve the storage pools in a cluster. This resource type was introduced with ONTAP 9.11.1.

.Ports

Storage ports of the cluster. This resource type was introduced with ONTAP 9.6 and enhanced with ONTAP 9.11.1.

.QOS policies

Quality of service policy configuration. This resource type was introduced with ONTAP 9.6.

.QOS options

Endpoints have been introduced to allow you to retrieve and set QOS options for the cluster. For example, you can reserve a percentage of available system processing resources for background tasks. This resource type was introduced with ONTAP 9.14.

.QOS workloads

A QOS workload represents a storage object tracked by QOS. You can retrieve the QOS workflows. This resource type was introduced with ONTAP 9.10.

.Qtrees

You can use these API calls to management Qtrees, a type of logically divided file system. This resource type was introduced with ONTAP 9.6. The qtree extended performance monitoring feature was added with ONTAP 9.16.1.

.Quota reports

Report on quotas, which is a technique for restricting or tracking files or space usage. This resource type was introduced with ONTAP 9.6.

.Quota rules

The rules used to enforce the quotas. This resource type was introduced with ONTAP 9.6 and updated with ONTAP 9.7.

.Shelves

Shelves in the cluster. This resource type was introduced with ONTAP 9.6.

.Snapshot policies

Snapshots are created based on policies. This resource type was introduced with ONTAP 9.6.

.Snapshot schedules

You can control the snapshot schedules. This resource type is newly redesigned with ONTAP 9.8.

.Switches

You can retrieve the switches in a cluster. This resource type was introduced with ONTAP 9.9.

.Tape devices

You can retrieve the tape devices in a cluster. This resource type was introduced with ONTAP 9.9.

.Top metrics

The top metrics endpoints allow you to determine activity for a volume filtered by a specific metric. Filtering can be done based on clients, directories, files, and users. This resource type was introduced with ONTAP 9.10.

.Volume efficiency policies

You can use these API calls to configure the efficiencies applied to an entire volume. This resource type is new with ONTAP 9.8.

.Volumes

Logical containers are used to serve data to clients. This resource type was originally introduced with ONTAP 9.6 REST API. Many of the parameter values used with the API were significantly expanded with ONTAP 9.9 including those used with space management.

.Volume files

You can retrieve a list of files and directories for a specific directory on a volume. This resource type was introduced with ONTAP 9.7 and updated with ONTAP 9.8.

.Volumes Snapshots

Snapshots for a volume. This resource type was introduced with ONTAP 9.6.
