---
sidebar: sidebar
permalink: resources/support.html
keywords:
summary:
---

= Support
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use these API calls to manage the ONTAP features used to support a cluster.

.Application log

A standalone application can record EMS events and optionally generated AutoSupport packages at an ONTAP system by issuing a POST request. This resource type was introduced with ONTAP 9.11.1.

.Automatic update

The automatic update feature keeps your ONTAP systems current by downloading and applying the latest software updates. There are several endpoint categories to support the feature, including status, configurations, and updates. These resource types were introduced with ONTAP 9.10.

.AutoSupport

AutoSupport collects configuration and status details as well as errors, and reports the information to NetApp. This resource type was introduced with ONTAP 9.6.

.AutoSupport messages

Each node maintains AutoSupport messages that can be generated and retrieved. This resource type was introduced with ONTAP 9.6.

.Configuration backup

You can use these APIs to retrieve and update the current backup settings. This resource type was introduced with ONTAP 9.6.

.Configuration backup operations

You can create, retrieve, and delete configuration backup files. This resource type was introduced with ONTAP 9.7.

.Core dump

You can use these endpoints to retrieve and manage the memory core dumps generated by a cluster or node. This resource type was introduced with ONTAP 9.10.

.EMS

The event management system (EMS) collects events and sends notifications to one or more destinations. This resource type was introduced with ONTAP 9.6.

.EMS destinations

The EMS destinations determine how and where notifications are sent. This resource type was introduced with ONTAP 9.6.

.EMS destinations instance

An EMS destination instance is defined by type and location. This resource type was introduced with ONTAP 9.6.

.EMS events

This is a live collection of system events for the cluster. This resource type was introduced with ONTAP 9.6.

.EMS filters

The EMS filters collectively identify the events that require additional processing. This resource type was introduced with ONTAP 9.6.

.EMS filters instance

An EMS filter instance is a collection of rules that are applied to the events. This resource type was introduced with ONTAP 9.6.

.EMS messages

Provides access to the EMS event catalog. This resource type was introduced with ONTAP 9.6.

.EMS rules for filter instance

A list of rules can be managed for a specific instance of an EMS filter. This resource type was introduced with ONTAP 9.6.

.EMS rules instance for filter instance

An individual rule for a specific instance of an EMS filter. This resource type was introduced with ONTAP 9.6.

.SNMP

You can enable and disable SNMP and trap operations for the cluster. This resource type was introduced with ONTAP 9.7.

.SNMP trap host

An SNMP trap host is a system that is configured to receive SNMP traps from ONTAP. You can retrieve and define the hosts. This resource type was introduced with ONTAP 9.7.

.SNMP trap host instance

You can manage specific SNMP trap hosts. This resource type was introduced with ONTAP 9.7.

.SNMP users

You can define and administer SNMP users. This resource type was introduced with ONTAP 9.7.

.SNMP users instance

You can administer a specific SNMP user where the engine ID is associated with the administrative SVM or a data SVM. This resource type was introduced with ONTAP 9.7.
