---
sidebar: sidebar
permalink: migrate/blogs_migrate.html
keywords: blogs, blog articles
summary: There are several blog articles available to help you better understand how to migrate from ONTAPI to the ONTAP REST API.
---

= Blog articles
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
There are several blog articles available to help you better understand how to migrate from ONTAPI to the ONTAP REST API.

.ONTAPI to REST Mapping

NetApp provides support for moving from the proprietary ONTAPI API to the ONTAP REST API through mapping documentation.

https://netapp.io/2020/12/17/ontapi-to-rest-mapping/[netapp.io/2020/12/17/ontapi-to-rest-mapping^]

.Transform your Automation to ONTAP REST API from ONTAPI

There are several technologies available to help you transform your ONTAP automation environment based on the REST API.

https://www.netapp.com/blog/transform-automation-ontap-rest-api/[www.netapp.com/blog/transform-automation-ontap-rest-api^]

.Using the private CLI passthrough with the ONTAP REST API

To help CLI and ONTAP users transition to the ONTAP REST API, ONTAP provides a private REST API endpoint that can be used to access any CLI command.

https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/[https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api^]

.Transitioning from ONTAPI using ONTAPI Usage Reporting Tool

NetApp provides a tool to help customers and partners transition to the ONTAP REST API.

https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/[netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool^]
