---
sidebar: sidebar
permalink: migrate/migration-considerations.html
keywords: snapdiff, migrating to rest
summary: 
---

= Migration considerations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
XXX

ONTAPI is a set of API calls provided through the Network Manageability SDK that can be used to administer ONTAP storage systems. There are differences between the REST API and the ONTAPI API calls, as well as between the REST API and ONTAP CLI. You should understand these differences before using the REST API in a production environment.

== General design differences

The ONTAP REST API and command line interface have a fundamentally different designs. The CLI commands and parameters do not map directly to the REST API calls. And even where there might be a similarity, the details of the input parameters can be different. For example, numeric units might be specified in bytes or using a suffix (such as KB). You should review link:input_variables.html[Input variables controlling an API request] as well as the link:../reference/api_reference.html[API reference] for more information.

== Data SVMs exposed through the REST API

ONTAP supports several types of storage virtual machines (SVMs). However, only the data SVMs are directly exposed through the ONTAP REST API. The configuration information describing the cluster and nodes is available through the REST API, however the cluster and nodes are not treated as separate SVMs.

== Migrating from ONTAPI to REST

The REST API is the primary and strategic choice for automating ONTAP system administration. If you are currently using the ONTAPI API, you should consider migrating to the REST API. NetApp provides mapping documentation to assist with the migration from ONTAPI to REST. See link:../migrate/mapping.html[ONTAPI to REST API mapping] for more information.


== Changes to SnapDiff availability in ONTAPI

Beginning with ONTAP 9.10.1, the SnapDiff v1 and v2 ONTAPI calls cannot be invoked. Any third-party application that invokes SnapDiff v1 or v2 ONTAPI calls will not function beginning with ONTAP 9.10.1. ONTAP users should verify that their backup application supports the SnapDiff v3 REST calls before upgrading to ONTAP 9.10.1.

SnapDiff API availability across ONTAP releases is defined as follows:

* ONTAP 9.7 and earlier releases:  v1 and v2 (ONTAPI only)
* ONTAP 9.8 – 9.9.1:  v1, v2 and v3 (both ONTAPI and REST API)
* ONTAP 9.10.1:  v3 only (REST API only)

For more information, see the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^].

.Related information

* link:../rest/input_variables.html[Input variables controlling an API request]
* link:../migrate/mapping.html[ONTAPI to REST API mapping]
