---
sidebar: sidebar
permalink: migrate/overview.html
keywords: ONTAPI, migrate, migrate to REST API
summary: If you are using the ONTAPI API, you are encouraged to begin migrating to the ONTAP REST API.
---

= ONTAPI disablement
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The ONTAPI API (ZAPI) is the original set of proprietary calls included with the NetApp ONTAP software. The API is provided through the Network Manageability SDK and supports the automation of data storage administration and management tasks. The ONTAPI interface will be disabled in future versions of ONTAP. If you are using ONTAPI, you should plan your migration to the ONTAP REST API.

NetApp first introduced the REST API with ONTAP 9.6. Since then the REST API has continued to expand and mature. It now provides the preferred and strategic option when automating the administration of your ONTAP deployments. There are many helpful resources and tools available to support your migration.

.Related information

* https://mysupport.netapp.com/info/communications/ECMLP2880232.html[CPC-00410 End of availability: ONTAPI^]
* https://kb.netapp.com/onprem/ontap/dm/REST_API/FAQs_on_ZAPI_to_ONTAP_REST_API_transformation_for_CPC_(Customer_Product_Communiques)_notification[FAQs on ZAPI to ONTAP REST API transformation for CPC^]