---
sidebar: sidebar
permalink: migrate/performance-counters.html
keywords:
summary:
---

= Migrate to REST API for performance counters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The ONTAP counter management system provides metrics on behavior of the ONTAP system. You can export counter information from the system to gain insight in to how ONTAP is performing, and help troubleshoot performance bottlenecks or get a baseline for system performance.

== Accessing performance counters using ONTAP APIs
Using the ONTAP API (ONTAPI), you can access performance counter information and export many different performance counter metrics. ONTAPI access to performance counter information will soon be deprecated in ONTAP and replaced with the ONTAP REST API. NetApp recommends transitioning your scripts and code that access performance counters to the ONTAP REST API as soon as possible.

With ONTAPI, you accessed performance counter data as objects. With the ONTAP REST API, you now access performance counter data as tables. This means that each performance counter is represented as its own table, while instances of that performance counter each become accessible as a row in that table. You can access individual attributes of a single instance (such as the name of a disk) as a field in that instance row.

.ONTAPI
<show an ONTAPI performance counter object represented with ONTAPI>

.ONTAP REST API
In the following example, the `host_adapter` performance counter is represented in table format, to illustrate how you would access each counter using the ONTAP REST API. For example, to access the `bytes_read` metric for host_adapter_2, you would use the following format: `host_adapter_2.bytes_read`.

//.Host adapter performance counter table
|===
|Instance name 6+|REST counters

|host_adapter_1
|total_read_ops
|total_write_ops
|bytes_read
|bytes_written
|max_link_data_rate
|rscn_count

|host_adapter_2
|total_read_ops
|total_write_ops
|bytes_read
|bytes_written
|max_link_data_rate
|rscn_count

|host_adapter_3
|total_read_ops
|total_write_ops
|bytes_read
|bytes_written
|max_link_data_rate
|rscn_count

|===

== REST API examples

<show three examples of using REST to get certain perf ctr info>

/api/cluster/counter/tables/{counter_table.name}/rows
so, then:
`GET /api/cluster/counter/tables/disk/rows` would retrieve all instances of the "disk" performance counter object (would this list all available REST perf counters for all disks?)

What call would you use to get the name of an individual disk?

What call would you use to get the raid group of all disks?

.Example request:

[source,curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/cluster/counter/tables/disk/rows/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent'
----

.Example response:
----


----


== ONTAPI to REST API migration resources

NetApp has several resources available that can help you migrate from NetApp ONTAPI to REST API in your environment:

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2882104[ONTAPI to ONTAP REST API mapping^]
