---
sidebar: sidebar
permalink: migrate/performance-counters.html
keywords: performance, performance counters, mapping
summary: The ONTAP Counter Manager maintains extensive information about the performance of each ONTAP system. It exports this data as performance counters you can use to assess the performance of your ONTAP system and help meet your performance goals.
---

= Performance counters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The ONTAP Counter Manager maintains extensive information about the performance of each ONTAP system. It exports this data as a set of _performance counters_ you can use to assess the performance of your ONTAP system and help meet your performance goals.

== Access the ONTAP performance counters

You can access the ONTAP performance counters using two different APIs as well as through the ONTAP command line interface.

[NOTE]
The ONTAP REST API is the preferred and strategic option when automating the administration of your ONTAP deployments.

.ONTAPI API
The ONTAPI API is available with the NetApp Network Manageability SDK. When using ONTAPI, the performance counters are defined within a collection of objects. Each object corresponds to a physical or virtual component of the system. There can be one or more instances of each object based on the system configuration.

For example, if your ONTAP system has four physical disks, there will be four instances of the `disk` object, each with its own set of performance counters. You can use ONTAPI to access the individual counters for each disk instance.

.ONTAP REST API
Beginning with ONTAP 9.11.1, you can also access the same performance data through the REST API. With the REST API, the performance counters are organized in tables which are roughly equivalent to the ONTAPI objects. Each table row is equivalent to an instance of an ONTAPI object.

For example, if your ONTAP system has four physical disks, the `disk` table will contain four rows. Each of the rows can be accessed individually and includes its own set of performance counters available as fields or columns in the row.

== Prepare to use the REST API

You should prepare before using the ONTAP REST API to access the performance counters.

=== Performance counters organized in tables

A subset of the ONTAPI objects is available through the ONTAP REST API and presented as tables. For example, the ONTAPI *hostadapter* object is available through the REST API as the *host_adpater* table. If there are several host adapters in the system, each is a table row with its own set of performance counters.

|===
|Instance name 6+|Performance counters

|host_adapter_1
|total_read_ops_1
|total_write_ops_1
|bytes_read_1
|bytes_written_1
|max_link_data_rate_1
|rscn_count_1

|host_adapter_2
|total_read_ops_2
|total_write_ops_2
|bytes_read_2
|bytes_written_2
|max_link_data_rate_2
|rscn_count_2

|host_adapter_3
|total_read_ops_3
|total_write_ops_4
|bytes_read_3
|bytes_written_3
|max_link_data_rate_3
|rscn_count_3
|===

=== Summary of the REST endpoints

There are four major endpoints available to access the performance counters and related tables.

[NOTE]
Each of the REST endpoints provides read-only access and supports only the *GET* HTTP method.

* /cluster/counter/tables
+
Returns a collection of counter tables and their schema definitions.

* /cluster/counter/tables/{name}
+
Returns information about a single named counter table.

* /cluster/counter/tables/{counter_name}/rows
+
Returns a collection of rows from a named counter table.

* /cluster/counter/tables/{counter_name}/rows/{id}
+
Returns a specific row from a named counter table.

=== ONTAPI objects to REST tables

NetApp provides extensive support for migrating your automation code from ONTAPI to the ONTAP REST API. This includes mapping documentation to identity the equivalent performance counter table available in the REST API for a given ONTAPI object.

See the appropriate documentation based on the ONTAP release you are using:

* https://docs.netapp.com/us-en/ontap-pcmap-9121/[ONTAP 9.12.1 performance counter mapping^]
* https://docs.netapp.com/us-en/ontap-pcmap-9111/[ONTAP 9.11.1 performance counter mapping^]

== Get started with the ONTAP REST API

You can review the following examples to better understand how to use REST API to access the ONTAP performance counters. This includes retrieving a list of the available tables as well as exploring the table structure.

=== Before you begin

Review the following information before using the examples.

.ONTAP credentials
You'll need an ONTAP administrator account including the password.

.Cluster management IP
You'll need the cluster management IP address configured for your ONTAP system.

.All API calls use the GET method
All of the examples can be used to retrieve information using the HTTP GET method.

.Variable substitution
Each curl example includes one or more variables as indicated with capitals and bracketed text. Make sure to replace these variables with actual values as appropriate for your environment.

.Examples match endpoints
The sequence of examples parallels the summary of the endpoints.
*<LINK>*

=== Available tables containing performance counters

You can use this REST API call to discover all of the counter manager tables available to query.

// --location --include
.Curl example
[%collapsible%open]
====
[source,curl]
----
curl --request GET --user admin:<PASSWORD> --insecure 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables'
----
====

.JSON output example
[%collapsible%open]
====
[source,json]
----
{}
----

=== Description and metadata for a specific performance counter table

You can use this REST API call to display the description and metadata for a specific table. The output includes the purpose of the table and what type of data each performance counter contains. The *host_adapter* table is used in this example.

.Curl example
[%collapsible%open]
====
[source,curl]
----
curl --request GET --user admin:<PASSWORD> --insecure 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter'
----
====

.JSON output example
[%collapsible%closed]
====
[source,json]
----
{}
----
====

=== View the rows in a performance counter table

You can use this REST API call to view the rows in a table, which tells you what instances of the counter manager objects exist.

.Curl example
[%collapsible%open]
====
[source,curl]
----
curl --request GET --user admin:<PASSWORD> --insecure 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter/rows'
----
====

.JSON output example
[%collapsible%closed]
====
[source,json]
----
{}
----
====

=== Query a specific counter manager instance

You can use this REST API call to view performance counter values for a specific counter manager instance in the table. In this example, the performance counter information for one of the power supplies in the system is requested.

.Curl example
[%collapsible%open]
====
[source,curl]
----
curl --request GET --user admin:<PASSWORD> --insecure 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter/rows/power-01:0b'
----
====

.JSON output example
[%collapsible%closed]
====
[source,json]
----
{}
----
====
