---
sidebar: sidebar
permalink: migrate/performance-counters.html
keywords: performance, performance counters, mapping
summary: The ONTAP Counter Manager maintains extensive information about the performance of each ONTAP system. It exports this data as performance counters which you can use to assess the performance of your ONTAP system and help meet your performance goals.
---

= Performance counters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The ONTAP Counter Manager maintains extensive information about the performance of each ONTAP system. It exports this data as _performance counters_ which you can use to assess the performance of your ONTAP system and help meet your performance goals.

== Access the ONTAP performance counters

You can access the ONTAP performance counters using two different APIs.

[NOTE]
The ONTAP REST API provides the preferred and strategic option when automating the administration of your ONTAP deployments.

.ONTAPI API
The ONTAPI API is available through the NetApp Network Manageability SDK. With ONTAPI, the performance counters are defined as objects. Each object can have one or more instances depending on the system configuration.

For example, if your ONTAP system has four physical disks, there are four instances of the `disk` object, each with its own set of performance counters. You can use ONTAPI to access the individual counters for each disk instance. Access to the full set of ONTAP Counter Manager objects is also provided through the ONTAP CLI interface.

.REST API
Beginning with ONTAP 9.11.1, you can access the same data through the ONTAP REST API. With the REST API, the performance counters are organized into tables which are roughly equivalent to the ONTAPI objects. Each table row is equivalent to an instance of an object when using ONTAPI.

For example, if your ONTAP system has four physical disks, the `disk` table contains four rows. Each of the rows can be accessed individually and contains its own set of performance counters available as fields or columns in the row.

== Prepare to use the REST API

You should prepare before using the ONTAP REST API to access the performance counters.

=== Performance counters organized in tables

A subset of the ONTAPI objects is available as tables through the ONTAP REST API. A simple example is presented below to illustrate this organization.

The ONTAPI *hostadapter* object is now available as the *host_adpater* table through the REST API. There are several host adapters in the system and each host adapter has its own performance counters.

//|Instance name 6+|REST counters
//[cols="25,75"*,options="header"]
//[cols="1,6",options="header"]
|===
|Instance name 6+|Performance counters

|host_adapter_1
|total_read_ops_1
|total_write_ops_1
|bytes_read_1
|bytes_written_1
|max_link_data_rate_1
|rscn_count_1

|host_adapter_2
|total_read_ops_2
|total_write_ops_2
|bytes_read_2
|bytes_written_2
|max_link_data_rate_2
|rscn_count_2

|host_adapter_3
|total_read_ops_3
|total_write_ops_4
|bytes_read_3
|bytes_written_3
|max_link_data_rate_3
|rscn_count_3
|===

=== Summary of the REST endpoints

xxx

* /cluster/counter/tables
+
xxx

* /cluster/counter/tables/{name}
+
xxx

* /cluster/counter/tables/{counter_name}/rows
+
xxx

* /cluster/counter/tables/{counter_name}/rows/{id}
+
xxx

=== ONTAPI objects to REST tables

NetApp provides extensive support for migrating your automation code from ONTAPI to the ONTAP REST API. This includes mapping documentation to identity the equivalent performance counter table in the REST API for a given ONTAPI object.

See the appropriate documentation based on the ONTAP release you are using:

* https://docs.netapp.com/us-en/ontap-pcmap-9121/[ONTAP 9.12.1 performance counter mapping^]
* https://docs.netapp.com/us-en/ontap-pcmap-9111/[ONTAP 9.11.1 performance counter mapping^]

== Get started with the ONTAP REST API

xxx

=== Before you begin

xxx
>> Need ONTAP credentials
>> All GET
>> Make titles of four sections below consistent
>> Review curl and use of abbreviations (use for string)

== Understanding the structure with REST API examples
Use the following REST API examples to help understand the structure of a counter manager table. These examples also show you how you can use the REST API to discover what endpoints are available, and use them to gain insight into the performance of your system. These examples explore the `host_adapter` counter manager object, showing progressively more detailed information about the object and the counter values it contains. If you try these examples on your system, be sure to provide your values for information in brackets <> where indicated.

=== Discover the available performance counter tables
You can use this REST API call to discover all of the counter manager tables that you can query:

.Curl example
[%collapsible%open]
====
[source,curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables'
----
====

.Example response (truncated for brevity):
[source,json]
----
{
  "records": [
    {
      "name": "copy_manager",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/copy_manager"
        }
      }
    },
    {
      "name": "copy_manager:constituent",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/copy_manager%3Aconstituent"
        }
      }
    },
    {
      "name": "disk",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/disk"
        }
      }
    },
    {
      "name": "host_adapter",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter"
        }
      }
    }
    ...
  ],
  "num_records": 68,
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables"
    }
  }
}
----

=== Query an individual performance counter table
You can use this REST API call to view the description and metadata for one specific table (counter manager object). The output describes the purpose of the table and also describes what type of information each performance counter in the table records. In this example, we query the `host_adapter` table:

.Curl example
[%collapsible%open]
====
[source,curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter'
----
====

.JSON output example
[%collapsible%closed]
====
[source,json]
----
{
  "name": "host_adapter",
  "description": "The host_adapter table reports activity on the Fibre Channel, Serial Attached SCSI, and parallel SCSI Host Adapters the storage system uses to connect to disks and tape drives.",
  "counter_schemas": [
    {
      "name": "bytes_read",
      "description": "Bytes read via Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    },
    {
      "name": "bytes_written",
      "description": "Bytes written via Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    },
    {
      "name": "max_link_data_rate",
      "description": "Max link data rate in Kilobytes per second for Host Adapter",
      "type": "raw",
      "unit": "kb_per_sec"
    },
    {
      "name": "node.name",
      "description": "System node name",
      "type": "string",
      "unit": "none"
    },
    {
      "name": "rscn_count",
      "description": "Number of RSCN(s) received by the FC HBA",
      "type": "raw",
      "unit": "none"
    },
    {
      "name": "total_read_ops",
      "description": "Total number of reads on Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    },
    {
      "name": "total_write_ops",
      "description": "Total number of writes on Host Adapter",
      "type": "rate",
      "unit": "per_sec"
    }
  ],
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables/host_adapter"
    }
  }
}
----
====

=== View the rows in a performance counter table
You can use this REST API call to view the rows in a table, which tells you what instances of the counter manager object exist:

.Curl example
[%collapsible%open]
====
[source,curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter/rows'
----
====

.JSON output example
[%collapsible%closed]
====
[source,json]
----
{
  "records": [
    {
      "id": "power-01:0b",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0b"
        }
      }
    },
    {
      "id": "power-01:0c",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0c"
        }
      }
    },
    {
      "id": "power-01:0d",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0d"
        }
      }
    },
    {
      "id": "power-01:0e",
      "_links": {
        "self": {
          "href": "/api/cluster/counter/tables/host_adapter/rows/power-01%3A0e"
        }
      }
    }
  ],
  "num_records": 4,
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables/host_adapter/rows"
    }
  }
}
----
====

=== Query a specific counter manager instance
You can use this REST API call to view performance counter values for a specific counter manager instance in the table. In this example, we request performance counter information for one of the power supplies in the system:

.Curl example
[%collapsible%open]
====
[source,curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<ONTAP_IP_ADDRESS>/api/cluster/counter/tables/host_adapter/rows/power-01:0b'
----
====

.JSON output example
[%collapsible%closed]
====
[source,json]
----
{
  "counter_table": {
    "name": "host_adapter"
  },
  "id": "power-01:0b",
  "properties": [
    {
      "name": "node.name",
      "value": "power-01"
    }
  ],
  "counters": [
    {
      "name": "total_read_ops",
      "value": 3600516
    },
    {
      "name": "total_write_ops",
      "value": 3591536
    },
    {
      "name": "bytes_read",
      "value": 86354320000
    },
    {
      "name": "bytes_written",
      "value": 480863081920
    },
    {
      "name": "max_link_data_rate",
      "value": 375000
    },
    {
      "name": "rscn_count",
      "value": 0
    }
  ],
  "_links": {
    "self": {
      "href": "/api/cluster/counter/tables/host_adapter/rows/power-01:0b"
    }
  }
}
----
====
