---
sidebar: sidebar
permalink: migrate/performance-counters.html
keywords:
summary: Transition from the ONTAPI to the ONTAP REST API for access to ONTAP performance counters.
---

= Performance counters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Using the ONTAP API (ONTAPI), you can access performance counter information and export many different ONTAP performance counter metrics. ONTAPI access to performance counter information will soon be deprecated in ONTAP and replaced with the ONTAP REST API. NetApp recommends transitioning your scripts and code that access performance counters to the ONTAP REST API as soon as possible.

== Accessing performance counters using ONTAPI
Until now, performance counter data was represented as objects. For example, a node with four disks would have four individual instances of the disk performance counter entity, and you could use ONTAPI to access individual performance counter objects within each entity instance.

== Accessing performance counters using the ONTAP REST API
With the ONTAP REST API, you now access performance counter data as tables. This means that each performance counter object is represented as its own table, while instances of that performance counter each become accessible as a row in that table. You can access individual attributes of a single instance (such as the name of a disk) as a field in that instance row.

In the following example, the `host_adapter` performance counter is represented in table format to illustrate how you would access each counter using the ONTAP REST API. For example, to access the `bytes_read` metric for host_adapter_2, you would use the following format: `host_adapter_2.bytes_read`.

//.Host adapter performance counter table
|===
|Instance name 6+|REST counters

|host_adapter_1
|total_read_ops
|total_write_ops
|bytes_read
|bytes_written
|max_link_data_rate
|rscn_count

|host_adapter_2
|total_read_ops
|total_write_ops
|bytes_read
|bytes_written
|max_link_data_rate
|rscn_count

|host_adapter_3
|total_read_ops
|total_write_ops
|bytes_read
|bytes_written
|max_link_data_rate
|rscn_count

|===

== REST API examples

<show three examples of using REST to get certain perf ctr info>

/api/cluster/counter/tables/{counter_table.name}/rows
so, then:
`GET /api/cluster/counter/tables/disk/rows` would retrieve all instances of the "disk" performance counter object (would this list all available REST perf counters for all disks?)

What call would you use to get the name of an individual disk?

What call would you use to get the raid group of all disks?

.Example request:

[source,curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/cluster/counter/tables/disk/rows/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent'
----

.Example response:
----


----


== ONTAPI to REST API migration resources

NetApp has several resources available that can help you migrate from NetApp ONTAPI to REST API in your environment:

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2882104[ONTAPI to ONTAP REST API mapping^]
* https://netapp-my.sharepoint.com/:u:/p/bmah/EQ8OiNnCNGpEhZKKbY3LkAQBsv-u5vteEKoEmq1Gm0QK1A?e=cM2noj[Performance counter REST API reference documentation]
