---
sidebar: sidebar
permalink: migrate/software.html
keywords:
summary:
---

= Tools and software supporting the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp provides sample Python scripts and other related software to support your migration from ONTAPI to the ONTAP REST API. The most important of these samples are described below.

[NOTE]
All the Python code samples are available at the https://github.com/NetApp/ontap-rest-python[NetApp ONTAP REST Python^] GitHub repository. You should also review the resources available in link:../additional/learn_more.html[Learn more about the ONTAP REST API].

== ONTAPI usage reporting tool

The ONTAPI usage reporting tool is designed to help NetApp professional services, customers, and partners identify the ONTAPI usage in their ONTAP environment. Scripts are provided for three different use cases as described in the table below.

[cols="20,80"*,options="header"]
|===
|Script |Description

|apache_scraper.py
|An Apache log scraper to find the ONTAPI calls issued against the ONTAP nodes
|session_stats.py
|A CLI script to retrieve session statistics data from ONTAP
|zapi_to_rest.py
|A script to extract the REST details of the ONTAPI calls and attributes passed
|===

You can access the https://github.com/NetApp/ontap-rest-python/tree/master/ONTAPI-Usage-Reporting-Tool[ONTAPI usage reporting tool^] to get started. Also see a https://www.youtube.com/watch?v=gJSWerW9S7o[Demo^] about the reporting tool and how to use it.

== Private CLI passthrough

The REST API provides broad coverage of the features and facilities available with ONTAP. However, there may be instances when direct access to the ONTAP CLI through the REST API can be useful.

For an introduction to this feature, see link:../rest/access_ontap_cli.html[Access the ONTAP CLI through the REST API]. For the Python samples see https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples[REST CLI passthrough samples^].

== Python client library

The Python client library is a package you can install and use to access the ONTAP REST API with Python. It allows you to quickly develop robust code for the automation of your ONTAP deployments. To learn more about the Python client library, refer to link:../python/learn-about-pcl.html[Python client library].

== ONTAP PowerShell Toolkit

The NetApp.ONTAP PowerShell Toolkit enhances your local PowerShell environment with a module that includes over 2,400 cmdlets. It allows you to quickly develop code for your Windows host to automate the ONTAP deployments. For more information, see link:../pstk/learn-about-pstk.html[Learn about the NetApp PowerShell Toolkit].
