---
sidebar: sidebar
permalink: additional/learn_more.html
keywords: learn, learn more, more information, additional resources
summary: There are several additional resources you can access to get help and find more information about how to automate the deployment and administration of your ONTAP storage systems.
---

= Learn more about the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are several additional resources available to help you automate the deployment and administration of your ONTAP storage systems.

== Blog articles

The blog articles are arranged in several sections based on the subject.

=== General

* A good summary of the current ONTAP automation technologies.
+
https://www.netapp.com/blog/new-normal-for-automation[New normal for automation^]

* You can monitor ONTAP events to stay aware of the system activity. The configuration and management of these events can be automated using the REST API.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification[ONTAP REST APIs: Automate Notification of High-Severity Events^]

* Coffee breaks with REST (6 episodes):
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852[Basics of ONTAP REST APIs^]
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208[Features of ONTAP REST APIs^]
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283[Getting Hands-on with ONTAP REST using Postman^]
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200[ONTAPI (ZAPI) Reporting tool^]
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293[Private CLI Passthrough^]
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604[5 magical features that make ONTAP storage automation simple!^]

=== Python client library

* This blog provides a good introduction to the features of the ONTAP Python client library.
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption[Simplify ONTAP REST API Consumption with the Python Client Library^]

=== Migrating to the REST API

* There are several technologies available to help you transform your ONTAP automation environment based on the REST API.
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/[Transform your Automation to ONTAP REST API from ONTAPI ^]

== Videos

* A good introduction to the NetApp Python client library and how to get started writing code using the library.
+
video::pg5ls1Ol6uw[youtube, width=848, height=480]
//https://www.youtube.com/watch?v=pg5ls1Ol6uw[Getting started with the NetApp ONTAP Python client library^]

* A look at the Ansible Certified Modules.
+
video::ZlmQ5IuVZD8[youtube, width=848, height=480]
+
video::L5DZBV_Sg9E[youtube, width=848, height=480]

* A collection of videos at NetApp TechComm TV.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_[Automate NetApp ONTAP Management^]

== NetApp Knowledge Base

* If you encounter an issue with the ONTAP REST API, you can report it to NetApp. 
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues[How to report issues on ONTAP REST API and ONTAP REST API Python client library^]

* If you identify a functional gap in the ONTAP REST API, you can request a new feature for the API.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API[How to request a feature for ONTAP REST API^]
