---
sidebar: sidebar
permalink: additional/resources.html
keywords: more information, additional resources
summary: There are several additional resources you can access to get help and find more information about how to automate the deployment and administration of your ONTAP storage systems.
---

= Additional resources
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are several additional resources available to help you automate the deployment and administration of your ONTAP storage systems.

== ONTAP 9 resources

* Provides documentation for the ONTAP 9 product family.
+
https://docs.netapp.com/us-en/ontap-family/[ONTAP 9 product documentation^]

* ONTAP 9 release notes with information about the current release.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^]

* Includes documentation and other helpful links you need to plan, administer, and support ONTAP 9.
+
https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx[ONTAP and ONTAP System Manager Resources^]

* Access the release notes and other documentation for previous ONTAP releases.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[ONTAP 9 Product Library^]

== ONTAP 9 developer resources

* Helps to get started with Ansible in a DevOps environment.
+
https://www.netapp.com/devops-solutions/ansible/[NetApp Ansible DevOps Solutions^]

* Provides the key ONTAPI calls and a mapping to the equivalent REST API calls. Select the appropriate ONTAP release.
+
link:../migrate/mapping.html[ONTAPI to REST API mapping]

* The NetApp Python Client Library package at PyPI.
+
https://pypi.org/project/netapp-ontap[PyPI: NetApp ONTAP^]

* Documentation for the NetApp Python Client Library.
+
https://library.netapp.com/ecmdocs/ECMLP2886776/html/index.html[NetApp PCL documentation for 9.14.1^]

* Provides resources and documentation needed to use the ONTAP REST API.
+
https://devnet.netapp.com/restapi.php[NetApp Developer Network: ONTAP RESTful API^]

== Blog articles

* The CLI passthrough provides a technique for executing ONTAP CLI commands using the REST API.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api[Using the private CLI passthrough with the ONTAP REST API^]

* If you're new to using Ansible for ONTAP automation, this is a good place to start.
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible[Getting Started with NetApp and Ansible: Install Ansible^]

== Videos

* A good introduction to the NetApp Python client library and how to get started writing code using the library.
+
https://www.youtube.com/watch?v=Wws3SB5d9Ss[Getting started with the NetApp ONTAP Python client library^]

* This video is also available through NetApp TV at link:https://tv.netapp.com/detail/video/6217195551001[Ansible Certified Modules^].
+
video::L5DZBV_Sg9E[youtube, width=848, height=480]

* A look at the Ansible Certified Modules.
+
video::ZlmQ5IuVZD8[youtube, width=848, height=480]

== NetApp resources

* Access troubleshooting tools, documentation, and technical support assistance.
+
https://mysupport.netapp.com/[NetApp Support^]

* Access requirements and compatibility information related to using ONTAP 9 and the ONTAP REST API.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]

* Access technical reports, white papers, and other documents.
+
http://www.netapp.com/us/library/index.aspx[NetApp library of technical reports and white papers^]
