---
sidebar: sidebar
permalink: additional/resources.html
keywords: more information, additional resources
summary: There are several additional resources you can access to get help and find more information about how to automate the deployment and administration of your ONTAP storage systems.
---

= Additional resources
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are several additional resources you can access to get help and find more information about how to automate the deployment and administration of your ONTAP storage systems.

== ONTAP 9 resources

* https://docs.netapp.com/us-en/ontap-family/[ONTAP 9 product documentation^]
+
Provides documentation for the ONTAP 9 product family.

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^]
+
ONTAP 9 release notes with information about the current release.

* https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx[ONTAP and ONTAP System Manager Resources^]
+
Includes documentation and other helpful links you need to plan, administer, and support ONTAP 9.

* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[ONTAP 9 Product Library^]
+
Access the release notes and other documentation for previous ONTAP releases.

== ONTAP 9 developer resources

//* https://library.netapp.com/ecm/ecm_download_file/ECMLP2882104[ONTAPI to REST API mapping information^]

* link:../migrate/mapping.html[ONTAPI to REST API mapping]
+
Provides the key ONTAPI calls and a mapping to the equivalent REST API calls. Select the appropriate ONTAP release.

* https://pypi.org/project/netapp-ontap[PyPI: NetApp ONTAP^]
+
The NetApp Python Client Library package at PyPI.

* https://library.netapp.com/ecmdocs/ECMLP2885777/html/index.html[NetApp PCL documentation for 9.13.1^]
+
Documentation for the NetApp Python Client Library.

* https://devnet.netapp.com/restapi.php[NetApp Developer Network: ONTAP RESTful API^]
+
Provides resources and documentation needed to use the ONTAP REST API, including the ONTAP Python client library.

== Videos

* https://www.youtube.com/watch?v=Wws3SB5d9Ss[Getting started with the NetApp ONTAP Python client library^]
+
Good introduction to the NetApp Python client library and how to get started writing code using the library.

== NetApp resources

* https://mysupport.netapp.com/[NetApp Support^]
+
Access troubleshooting tools, documentation, and technical support assistance.

* https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
+
Access requirements and compatibility information related to using ONTAP 9 and the ONTAP REST API.

* http://www.netapp.com/us/library/index.aspx[NetApp library of technical reports and white papers^]
+
Access technical reports, white papers, and other documents.
