---
sidebar: sidebar
permalink: reference/api_reference.html
keywords: reference, API reference, ONTAP API documentation
summary: The API reference contains the details about all the ONTAP REST API calls, including the HTTP methods, input parameters, and responses. This complete reference is helpful when developing automation applications using the REST API.
---

= API reference
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The API reference contains the details about all the ONTAP REST API calls, including the HTTP methods, input parameters, and responses. This complete reference is helpful when developing automation applications using the REST API.

[NOTE]
You can access the online API reference content at your local ONTAP system or a static copy of the documentation maintained by NetApp.

== Access the ONTAP API documentation page

[.lead]
You can access the ONTAP API online documentation page at your local ONTAP system.

.Before you begin

You must have the following:

* IP address or host name of the ONTAP cluster management LIF
* User name and password for an account with authority to access the ONTAP REST API

.Steps

. Type the URL in your browser and press *Enter*:
+
`https://<ip_address>/docs/api`
+
. Sign in using the ONTAP account.
+
The ONTAP API documentation page is displayed with the API calls organized in major resource categories at the bottom.
+
. As an example of an individual API call, scroll down to the *cluster* category and click *GET /cluster*.

== Access a copy of the ONTAP REST API reference documentation

[.lead]
You can access a copy of the ONTAP REST API reference documentation through the links provided below. The API reference documentation is maintained by ONTAP release.

* https://library.netapp.com/ecmdocs/ECMLP2882307/html/[ONTAP 9.11.1^]
* https://library.netapp.com/ecmdocs/ECMLP2879871/html/[ONTAP 9.10.1^]
* https://library.netapp.com/ecmdocs/ECMLP2876964/html/[ONTAP 9.9.1^]
* https://library.netapp.com/ecmdocs/ECMLP2874708/html/[ONTAP 9.8^]
* https://library.netapp.com/ecmdocs/ECMLP2862544/html/[ONTAP 9.7^]
* https://library.netapp.com/ecmdocs/ECMLP2856304/html/[ONTAP 9.6^]

.Related information

https://devnet.netapp.com/restapi.php[NetApp DevNet: ONTAP REST APIs^]
