---
sidebar: sidebar
permalink: reference/api_reference.html
keywords: reference, API reference, ONTAP API documentation, online reference, swagger
summary: "The API reference contains details about the ONTAP REST API calls, including the HTTP methods, input parameters, and responses. This complete reference is helpful when developing automation applications using the REST API."
---

= Reference for the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The API reference contains details about the ONTAP REST API calls, including the HTTP methods, input parameters, and responses. This complete reference is helpful when developing automation applications using the REST API.

[NOTE]
You can access the REST API reference documentation at one of several sites based on the ONTAP release. A copy of the equivalent documentation is also available through the Swagger UI at your local ONTAP system.

== Access the ONTAP API reference documentation online

You can access the current https://docs.netapp.com/us-en/ontap-restapi/getting_started_with_the_ontap_rest_api.html[ONTAP REST API reference^] documentation online. There is also a version selector available to access previous versions of the documentation based on the ONTAP release.

== Access the ONTAP API reference documentation through the Swagger UI

You can access the ONTAP REST API documentation through the Swagger UI at your local ONTAP system.

.Before you begin

You must have the following:

* IP address or host name of the ONTAP cluster management LIF
* User name and password for an account with authority to access the ONTAP REST API

.Steps

. Type the URL in your browser and press *Enter*:
+
`https://<ip_address>/docs/api`
+
. Sign in using the ONTAP account.
+
The ONTAP API documentation page is displayed with the API calls organized in major resource categories at the bottom.
+
. As an example of an individual API call, scroll down to the *cluster* category and click *GET /cluster*.
