---
sidebar: sidebar
permalink: nmsdk.html
keywords: 
summary: 
---

= NetApp Manageability SDK
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The NetApp Manageability SDK provides a set of API calls for developing applications to monitor and manage your ONTAP storage. Together with the OnCommand Workflow Automation package, the SDK supports your efforts to automate the manage of your ONTAP systems.

[NOTE]
While the NetApp Manageability SDK and OnCommand Workflow Automation continued to be supported, the ONTAP REST API is the preferred and strategic technology to use with your ONTAP automation systems.

You can download the SDK from the NetApp Support Site. The SDK supports several languages on the client side, including:

* Python
* PowerShell
* C
* C++
* Java
* C#
* VB.Net
* Ruby

You can also use SDK API to automate management tasks without writing scripts. OnCommand Workflow Automation (OnCommand WFA) provides several prepackaged workflows to deploy and run management tasks. You can download the OnCommand WFA package from the NetApp Storage Automation Store. Also review the Interoperability Matrix Tool for information about the NetApp Manageability SDK and OnCommand Workflow Automation as well as how they are supported with your version of ONTAP.

.Related information

* https://mysupport.netapp.com/site/[NetApp Support Site^]

* https://www.netapp.com/company/interoperability/[NetApp Interoperability Matrix Tool^]

* https://mysupport.netapp.com/documentation/docweb/index.html?productID=63638&language=en-US[NetApp Manageability SDK documentation^]

* https://www.netapp.com/data-management/oncommand-workflow-automation-documentation/[OnCommand Workflow Automation documentation resources^]

* https://automationstore.netapp.com/home.shtml[NetApp Automation Store^]