---
sidebar: sidebar
permalink: workflows/wf_1_update_cluster_contact.html
keywords: workflow
summary: This workflow updates the cluster contact information. Because the request is processed asynchronously, it also illustrates how to determine if the background job completes successfully.
---

= Workflow 1: Update the cluster contact and check job state
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This workflow updates the cluster contact information. Because the request is processed asynchronously, it also illustrates how to determine if the background job completes successfully.

=== 1. Update the contact information for the cluster

You can issue an API call to update the contact information. Because the request runs asynchronously, you must confirm success of the associated job.

|===
|Category |HTTP method |Path

|Cluster
|PATCH
|/cluster
|===

.Processing type
Asynchronous

.Curl

[source,curl,%autofill]
curl -X PATCH -H 'Content-Type: application/json' -u admin:password -k -d @step01 'https://10.222.81.101/api/cluster'
{
  "contact": "support@company-demo.com"
}

.JSON output
A job object with the associated identifier is returned.

[source,json,%autofill]
{ "job": {
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
  }
}

=== 2. Retrieve the status of the job

You must retrieve the state of the job to determine if the asynchronous request has completed successfully.

|===
|Category |HTTP method |Path

|Cluster
|GET
|/cluster/jobs/{uuid}
|===

.Processing type

Synchronous

.Curl

[source,curl,%autofill]
curl -X GET -H 'Content-Type: application/json' -u admin:password -k 'https:// 10.222.81.101/api/cluster/jobs/*uuid*'

.Output

A job object with the state and other fields is returned.

[source,json,%autofill]
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
