---
sidebar: sidebar
permalink: workflows/wf_cls_get_cluster.html
keywords: workflow, get cluster, cluster configuration
summary: You can retrieve the configuration for an ONTAP cluster including specific fields. You might do this as part of assessing the state of the cluster or before updating the configuration.
---

= Get cluster configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can retrieve the configuration for an ONTAP cluster including specific fields. You might do this as part of assessing the state of the cluster or before updating the configuration.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/api/cluster
|===

.Additional input parameters for curl examples

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl example in this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|fields
|Query
|No
|Select the values you want returned. Examples include `contact` and `version`.
|===

.Curl example: Retrieve the cluster contact information

This example illustrates how to retrieve a single field. To get the entire cluster object and configuration, you need to remove the `fields` query parameter.

[source,curl]
curl --request GET \
--location "https://$FQDN_IP/api/cluster?fields=contact" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"

.JSON output example
----
{
  "contact": "support@company-demo.com"
}
----