---
sidebar: sidebar
permalink: workflows/wf_cls_update_contact.html
keywords: workflow, update cluster, cluster contact
summary: You can update the contact information for a cluster. Because the request is processed asynchronously, you also need to determine if the associated background job completed successfully.
---

= Update cluster contact using the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can update the contact information for a cluster. Because the request is processed asynchronously, you also need to determine if the associated background job completed successfully.

== Step 1: Update the cluster contact information

You can issue an API call to update the cluster contact information.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|PATCH
|/api/cluster
|===

.Processing type

Asynchronous

.Curl example

[source,curl,%autofill]
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput

.JSON input example

[source,json]
{
  "contact": "support@company-demo.com"
}

.JSON output example

A job object is returned. You should save the job identifier to use it in the next step.

----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----

== Step 2: Retrieve the status of the job

Perform the workflow link:../workflows/wf_jobs_get_job.html[Get job instance] and confirm the `state` value is `success`.

== Step 3: Confirm the cluster contact information

Perform the workflow link:../workflows/wf_cls_get_cluster.html[Get cluster configuration]. You should set the `fields` query parameter to `contact`.
