---
sidebar: sidebar
permalink: workflows/wf_nas_fs_update_sd.html
keywords: 
summary: 
---

= Get the auditing information for a file
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can apply a new security descriptor to a specific file or folder.

== Step 1: Apply the new permissions

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/api/protocols/file-security/permissions/{svm.uuid}/{path}
|===

.Processing type

Synchronous

.Additional input parameters for curl examples

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl example in this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|$SVM_ID
|Path
|Yes
|This is the UUID of the SVM containing the file.
|$FILE_PATH
|Path
|Yes
|This is the path to the file or folder.
|===

.Curl example

[source,curl]
curl -u admin:<PASSWORD> -X POST -d '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0'

.JSON output example
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----

== Step 2: Retrieve the status of the job

Perform the workflow link:../workflows/wf_jobs_get_job.html[Get job instance] and confirm the `state` value is `success`.
