---
sidebar: sidebar
permalink: workflows/wf_nas_fs_update_sd.html
keywords: nas, file security, security descriptor, sd, update security descriptor
summary: You can update a specific security descriptor to a specific file or folder, including the primary owner, group, or control flags.
---

= Update security descriptor information using the ONTAP REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can update a specific security descriptor to a specific file or folder, including the primary owner, group, or control flags.

== Step 1: Update the security descriptor

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|PATCH
|/api/protocols/file-security/permissions/{svm.uuid}/{path}
|===

.Processing type

Asynchronous

.Additional input parameters for curl examples

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl example in this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|$SVM_ID
|Path
|Yes
|This is the UUID of the SVM containing the file.
|$FILE_PATH
|Path
|Yes
|This is the path to the file or folder.
|===

.Curl example

[source,curl]
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}'

.JSON output example
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----

== Step 2: Retrieve the status of the job

Perform the workflow link:../workflows/wf_jobs_get_job.html[Get job instance] and confirm the `state` value is `success`.
