---
sidebar: sidebar
permalink: python/learn-about-pcl.html
keywords: learn about python client library, learn about pcl, pcl overview, pcl
summary: "The NetApp ONTAP Python client library is a package you can install and use to quickly write scripts that access the ONTAP REST API. You'll need to prepare the local runtime environment before using it."
---

= Learn about the Python client library
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The NetApp ONTAP Python client library is a package you can install and use to quickly write scripts that access the ONTAP REST API. You'll need to prepare the local runtime environment before using it.

.Benefits and features

You can use the Python client library to quickly develop robust code to automate the administration of your ONTAP deployments. It provides several underlying services, including:

* Connection management
* Asynchronous processing
* Exception handling
* Uniform error messages

.Package name and version

The name of the Python client library package is *netapp-ontap*. The version associated with the package is a combination of the ONTAP major and minor version numbers the library was generated from, along with a minor version for the client library within the ONTAP release. For example, valid version numbers include 9.6.1, 9.6.2, and 9.7.1.

.Installation

You must use *pip* utility to install the netapp_ontap package from the Python Package Index (PyPi) site.

.Packages and documentation by ONTAP release

Each ONTAP release beginning with 9.6 has a PyPI package and associated documentation. See link:../python/packages.html[Packages and documentation] for more information. Installation requirements are included with each package and specify different versions of the following:

* python
* requests
* requests-toolbelt
* marshmallow

.Code samples

NetApp maintains a GitHub repository with code samples and other helpful information. You can navigate to the _examples_ folder to access samples using the Python client library. Refer to the following locations at GitHub for details:

* https://github.com/NetApp/ontap-rest-python[ONTAP REST Python GitHub repository^]

* https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library[ONTAP REST Python Client Library Examples^]
