---
sidebar: sidebar
permalink: python/overview_pcl.html
keywords:
summary:
---

= Overview of the Python client library
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

The NetApp ONTAP Python client library is a package you can install and use to write scripts that access the ONTAP REST API. It provides support for several underlying services, including connection management, asynchronous processing, exception handling, and error messages. By using the Python client library, you can quickly develop robust code to support the automation of ONTAP deployments.

[.lead]
Beginning with ONTAP 9.6, you have the option of using the Python client library to access the ONTAP REST API. The library provides a client-side development environment with several underlying services, such as connection management, asynchronous processing, exception handling, and error messages. After downloading and installing the ONTAP Python client library package, you can quickly create robust Python scripts to support the automation of your ONTAP deployments.

[NOTE]
NetApp maintains a GitHub repository containing code samples and other helpful information. You can navigate to the _examples_ folder to access samples using the Python client library.

.Related links

https://github.com/NetApp/ontap-rest-python[ONTAP REST Python GitHub repository^]
