---
sidebar: sidebar
permalink: python/prepare_pcl.html
keywords: python client library, prepare, pcl
summary: You should prepare the local runtime environment before using the Python client library.
---

= Prepare to use the Python client library
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You should prepare the local runtime environment before using the Python client library.

.Package name and version

The name of the Python client library package is *netapp-ontap*. The version associated with the package is a combination of the ONTAP major and minor version numbers the library was generated from, along with a minor version for the client within the ONTAP release. For example,  valid version numbers include: 9.6.1, 9.6.2, and 9.7.1.

.Installation

You must use pip to install the netapp_ontap package from the Python Package Index (PyPi) web site.

.Packages and documentation by ONTAP release

Each ONTAP release beginning with 9.6 has a PyPI package and associated documentation. See link:../python/packages.html[Packages and documentation] for more information. Installation requirements are include with each package and include different versions of the following:

* python
* requests
* requests-toolbelt
* marshmallow
