---
sidebar: sidebar
permalink: python/prepare_pcl.html
keywords: python client library, prepare, pcl
summary: You should prepare the local runtime environment before using the Python client library.
---

= Prepare to use the Python client library
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should prepare the local runtime environment before using the Python client library.

.Basic requirements

You must use Python 3.5 or later. In addition, the following packages are also required:

* requests 2.22.1 or later
* requests-toolbelt 0.9.1 or later
* marshmallow 3.2.1 or later

.Package name and version

The name of the Python client library package is *netapp-ontap*. The version associated with the package is a combination of the ONTAP major and minor version numbers the library was generated from, along with a minor version for the client within the ONTAP release. For example,  valid version numbers include: 9.6.1, 9.6.2, and 9.7.1.

.Installation

You must use pip to install the netapp_ontap package from the Python Package Index (PyPi) web site.

.Documentation and additional resources

See the _NetApp Developer Network_ for links to documentation and other resources.

.Related information

* https://pypi.org/project/netapp-ontap[PyPI: NetApp ONTAP 9.13.1^]
* https://library.netapp.com/ecmdocs/ECMLP2885777/html/index.html[NetApp PCL documentation for 9.13.1^]
* https://devnet.netapp.com/restapi.php[NetApp Developer Network: ONTAP RESTful API^]
