---
sidebar: sidebar
permalink: get-started/get_started_before.html
keywords:
summary:
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are several steps you should take to prepare to use the ONTAP REST API.

===== Experience with ONTAP 9

You should have experience with ONTAP 9. This includes understanding the basic concepts and terminology as well as some experience with system administration. See https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP 9 Concepts^] to get started.

===== Review REST concepts and implementation

Make sure to review link:understanding_rest.html[Understanding the ONTAP REST API] for information about REST concepts and details regarding how the ONTAP REST API is designed.

===== Software development background

It is helpful to have some experience with software development technologies and processes, including one or more programming languages as well as common utilities such as curl.

===== Get more information

You should be aware of the additional information resources as suggested in link:../resources/get_more_information.html[Get more information].
