---
sidebar: sidebar
permalink: get-started/ontap_automation_options.html
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog
summary: There are several options available to automate the deployment and administration of your ONTAP storage systems.
---

= Understand the ONTAP automation options
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are several options available to automate the deployment and administration of your ONTAP storage systems.

== ONTAP REST API

Beginning with ONTAP 9.6, ONTAP includes an expansive REST API that provides the foundation for automating the deployment and administration of your storage systems. Since then the REST API has continued to expand and mature. It now provides the preferred and strategic option when automating the administration of your ONTAP deployments. There are several considerations when using the ONTAP REST API.

.Accessing the REST API natively

You can access the ONTAP REST API directly using any programming language that supports a REST client. Popular language choices include Python, PowerShell, and Java.

.Migrating legacy ONTAPI code to use REST

The ONTAPI API (ZAPI) is the original set of proprietary calls included with the NetApp ONTAP software to support the automation of data storage administration and management tasks. The ONTAPI interface will be disabled in future versions of ONTAP. If you have existing code using the ONTAPI API, you should plan to migrate away from ONTAPI. NetApp provides support for converting your code to use the newer ONTAP REST API. See link:../migrate/ontapi_disablement.html[Migrate to the REST API] for more information.

== Client software toolkits

NetApp provides client toolkits that abstract the ONTAP REST API and make it easier to create automation code. You should choose one appropriate for your development language and environment.

.Python client library

The Python client library is a package you can use when writing scripts to access the ONTAP REST API. It provides support for several underlying services, including connection management, asynchronous request processing, and exception handling. By using the Python client library, you can quickly develop robust code to support your ONTAP automation goals. See link:../python/overview_pcl.html[Python client library] for more information.

.PowerShell toolkit

You can use the NetApp.ONTAP PowerShell Toolkit to automate the administration of an ONTAP cluster from a Windows host. See https://review.docs.netapp.com/us-en/ontap-automation_devnet-update/pstk/overview_pstk.html[Overview of the PowerShell Toolkit^] for more information.

== Automation frameworks

You can create and deploy automation code using one of several frameworks

.Ansible

Ansible is an open-source software tool that supports provisioning, configuration management, and application deployment. Since its release and subsequent acquisition by RedHat, it has continued to grow in popularity. NetApp provides Ansible-certified modules that customers can use to automate the administration of their ONTAP storage systems. See link:../additional/learn_more.html[Learn more] and https://www.netapp.com/devops-solutions/ansible/[NetApp Ansible DevOps Solutions^] for additional information.

.BlueXP automation catalog

The NetApp https://console.bluexp.netapp.com/automationCatalog/[BlueXP automation catalog^] is available through the BlueXP web user interface. The catalog provides access to packaged solutions that can help you to automate the deployment and integration of ONTAP with other products. See https://docs.netapp.com/us-en/netapp-automation/[NetApp automation^] for documentation and more information.
