---
sidebar: sidebar
permalink: get-started/ontap_automation_options.html
keywords: ontap automation, rest rest api, python client library, ansible
summary: Beginning with ONTAP 9.6, ONTAP includes an expansive REST API that provides the foundation for automating the deployment and administration of your storage systems. You can access the REST API directly or through the NetApp Python client library.
---

= Understand the ONTAP automation options
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.6, ONTAP includes an expansive REST API that provides the foundation for automating the deployment and administration of your storage systems. You can access the REST API directly or through the NetApp Python client library. In addition, NetApp supports ONTAP automation using Ansible as well as other high-level software abstractions.

[NOTE]
The ONTAPI API, also known as the Network Manageability SDK or ZAPI, is the legacy technology for programmatically accessing and administering ONTAP storage systems. The ONTAP REST API is now the strategic technology and should be selected where possible.

== Accessing the ONTAP REST API natively

You can access the ONTAP REST API directly using any programming language that supports a REST client. Popular language choices include Python, PowerShell, and Java. You should begin by reviewing all the documentation at this site.

== Adapt legacy ONTAPI code to use REST

If you have existing code using the ONTAPI API, NetApp provides support for converting your code to use the newer ONTAP REST API. See https://library.netapp.com/ecm/ecm_download_file/ECMLP2879870[ONTAPI to REST API mapping information^] for information about mapping the ONTAPI calls to the equivalent REST API calls.

== Using the NetApp Python client library

The Python client library is a package you can use when writing scripts to access the ONTAP REST API. It provides support for several underlying services, including connection management, asynchronous request processing, and exception handling. By using the Python client library, you can quickly develop robust code to support your ONTAP automation goals. You should begin by reviewing the documentation at this site, including link:../python/overview_pcl.html[Python client library].

== Using Ansible

Ansible is an open-source software tool that supports provisioning, configuration management, and application deployment. Since its release and subsequent acquisition by RedHat, it has continued to grow in popularity. NetApp provides Ansible-certified modules that customers can use to automate the administration of their ONTAP storage systems. You should begin by reviewing the documentation at this site, including link:../automate/ontap_ansible.html[ONTAP and Ansible automation].

== BlueXP automation catalog

The NetApp https://console.bluexp.netapp.com/automationCatalog/[BlueXP automation catalog^] is available through the BlueXP web user interface. The catalog provides access to solutions that can help you with the automated deployment and integration of ONTAP and other NetApp products. See the https://docs.netapp.com/us-en/netapp-automation/[NetApp automation^] documentation for a description of the automation solutions.
