---
sidebar: sidebar
permalink: get-started/prepare_workflows.html
keywords: workflows, preparation, prepare to use workflows
summary: You should be familiar with the structure and format of the ONTAP workflows before using them with a live deployment.
---

= Prepare to use the workflows
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should be familiar with the structure and format of the ONTAP workflows before using them with a live deployment.

== Introduction

A _workflow_ is a sequence of one or more steps needed to accomplish a specific administrative task or goal. The ONTAP workflows include the core steps and parameters you need to accomplish each task. They provide a starting point for customizing your ONTAP automation environment.

.Step types

Each step in an ONTAP workflow is one of the following types:

* REST API call (with details such as curl and JSON examples)
* Invocation of another ONTAP workflow
* Miscellaneous related task (such as making a configuration decision)

.REST API calls

Most of the workflow steps are REST API calls. These step types are based on a common format which includes curl examples and other information. See the link:../reference/api_reference.html[API reference] for details about the REST API calls.

.Single-step workflows

A workflow can contain only one step. These _single-step workflows_ are formatted slightly differently than workflows containing multiple steps. For example, the explicit step name is removed. The workflow action should be clear based on the title.

== Input variables and authentication

The workflows are designed to be general so they can be used in any ONTAP environment. The REST API calls use variables in the curl examples and other input which indicate how each needs to be tailored for your environment.

=== URL format

You can access the ONTAP REST API directly through curl or a programming language such as Python. In this case, the core URL is different than the URL used when accessing the ONTAP online documentation page or System Manager user interface. When accessing the API directly, you need to append *api* to the domain (or IP address) and port string. For example:

`https://ontap.demo-example.com/api`

See link:../rest/access_rest_api.html[How to access the ONTAP API] for more information about accessing the ONTAP REST API.

=== Common input parameters

There are several input parameters that are used in most of the REST API calls. These common parameters are typically not described in the individual workflows. You should be familiar with these parameters. See link:../rest/input_variables.html[Input variables controlling an API request] for more information.

If additional parameters are needed for a specific curl example, they are described in the section *Additional input parameters for the curl example* for each workflow.

=== Variable format

The ID values and other variables used with the curl examples are opaque and vary with each ONTAP cluster and runtime environment. To improve the readability of the samples, the actual values are not used. Rather, smaller reserved keywords are used instead. This approach has several benefits:

* The curl and JSON samples are more readable and easier to understand.
* Because all the keywords use the same format, you can quickly identify them.
* There is no security exposure because the original parameters cannot be copied and used.

The variables are formatted to be used in a Bash shell environment. Each variable begins with a dollar sign and is enclosed in double quotes as needed, which makes them recognizable to Bash. Upper case is consistently used for the names allowing them to be easily located.

Here are some of the common variable keywords. This list is not exhaustive and additional keywords are used as needed. Their meaning should be obvious based on the context.

[cols="25,15,60"*,options="header"]
|===
|Keyword
|Type
|Description
|$FQDN_IP
|URL
|The fully qualified domain name or IP management address for the ONTAP cluster.
|$CLUSTER_ID
|Path
|The UUIDv4 value identifying the ONTAP cluster where the API operation runs.
|$BASIC_AUTH
|Header
|The credentials string used for HTTP basic authentication. The string is encoded using base64.
|===

== Authentication options

The primary authentication method available for the REST API through ONTAP 9.13.1 is basic authentication.

=== HTTP basic authentication

When using basic authentication, the user credentials must be included with every HTTP request. There are two options for sending the credentials.

.Construct the HTTP request header

You can manually construct the Authorization header and include it with each HTTP request. This can be done when using a curl command in the CLI environment or a programming language with your customer automation code. The steps at a high level include:

. Concatenate the user and password values with a colon:
+
`admin:david123`

. Convert the string to base64:
+
`YWRtaW46ZGF2aWQxMjM=`

. Construct the request header:
+
`Authorization: Basic YWRtaW46ZGF2aWQxMjM=`

The workflow curl examples include this header with the variable *$BASIC_AUTH* which you need to update.

.Use a curl parameter

Another option when using curl is to remove the Authorization header and use the curl *user* parameter instead. For example:

`--user username:password`

You need to substitute the appropriate credentials for your environment. When executing the curl command with this parameter, the Authorization header will be generated for you.

== Using curl examples with the Bash shell

If you use the workflow curl examples directly, you must update the variables to use values appropriate for your environment. You can manually edit the example commands or rely on the Bash shell to do the substitution as described below.

.Steps

. Open the Bash shell provided with Linux or similar operating system.
. Set the variable values used in the curl command. For example:
+
`CLUSTER_ID=ce559b75-4145-11ee-b51a-005056aee9fb`
. Copy the curl example from the workflow page and paste it into shell terminal.
. Press *ENTER* which will do the following:
.. Substitute the variable values you set
.. Execute the curl command
