---
sidebar: sidebar
permalink: get-started/prepare_workflows.html
keywords: workflows, preparation, prepare to use workflows
summary: You should be familiar with the structure and format of the ONTAP workflows before using them with a live deployment.
---

= Prepare to use the workflows
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should be familiar with the structure and format of the ONTAP workflows before using them with a live deployment.

== Introduction

A _workflow_ is a sequence of one or more steps needed to accomplish a specific administrative task or goal. The ONTAP workflows include the core steps and parameters you need to accomplish each task. They provide a starting point for customizing your ONTAP automation environment.

.Step types

Each step in an ONTAP workflow is one of the following types:

* REST API call (with details such as curl and JSON examples)
* Invocation of another ONTAP workflow
* Miscellaneous related task (such as making a configuration decision)

.REST API calls

Most of the workflow steps are REST API calls. These step types are based on a common format which includes curl examples and other information. See the link:../reference/api_reference.html[API reference] for details about the REST API calls.

.Single-step workflows

A workflow can contain only one step. These _single-step workflows_ are formatted slightly differently than workflows containing multiple steps. For example, the explicit step name is removed. The workflow action should be clear based on the title.

== Input variables and authentication

The workflows are designed to be general so they can be used in any ONTAP environment. The REST API calls use input variables which have been tailored for the Bash shell environment.

=== URL format when directly accessing the REST API

You can access the ONTAP REST API directly through curl or a programming language such as Python. In this case, the core URL is different than the URL used when accessing the ONTAP online documentation or System Manager page. When accessing the API directly, you need to append `/api` to the domain (or IP address) and port string. For example:

`https://ontap.mycompany.com/api`

See link:../rest/access_rest_api.html[How to access the ONTAP API] for more information about accessing the API.

=== Common input parameters

There are several input parameters that are used across most of the workflows. These common parameters are typically not described in the individual workflows. See link:../rest/input_variables.html[Input variables controlling an API request] for more information.

If additional parameters are needed for a specific curl example, they are described in the section *Additional input parameters for the curl example* for each workflow.

=== Variable format

The ID values and other variables used with the curl examples are opaque and vary with each ONTAP cluster and runtime environment. To improve the readability of the samples, the actual values are not used. Rather, smaller reserved keywords are used instead. This approach has several benefits:

* The curl and JSON samples are clearer and easier to understand.
* Because all the keywords use the same format, you can quickly identify them.
* There is no security exposure because the original parameters cannot be copied and used.

Here are some of the common reserved keywords used in the curl examples. This list is not exhaustive and additional keywords are used as needed. Their meaning should be obvious based on the context.

[cols="25,15,60"*,options="header"]
|===
|Keyword
|Type
|Description
|$FQDN_IP
|URL
|The fully qualified domain name or IP management address for the ONTAP cluster.
|$CLUSTER_ID
|Path
|The UUIDv4 value identifying the account where the API operation runs.
|$BASIC_AUTH
|Header
|The credentials string used for HTTP basic authentication. This string is encoded using base64.
|===

=== Authentication options

The primary authentication technique available for the use with the REST API through ONTAP 9.13.1 is basic authentication.

==== HTTP basic authentication

When using basic authentication, the user credentials are included with every HTTP request. The user and password values are first concatenated with a colon and the entire string is encoded in base64. The string is then carried in an Authorization request header. The curl examples provided with the workflows include the header with the variable *$BASIC_AUTH*.

[NOTE]
When using a curl example to access the REST API, you can remove the Authorization header and add the user parameter instead. For example, you can specify `--user username:password` and curl will generate the header for you.

== Using the curl examples with the Bash shell

Each of the ONTAP workflows illustrates how to use the REST API to complete a specific task. You can review and adapt the curl examples to your automation development environment. You can also use the curl examples directly. This involves setting the variable values and then copying and pasting the curl command into the shell.

[NOTE]
The variables in the curl examples are formatted to be used in a Bash shell environment. Each variable begins with a dollar sign and is enclosed in double quotes as needed, which makes them recognizable to Bash. Upper case is consistently used for the names allowing them to be easily located.

.Steps

. Open the Bash shell provided with Linux or similar operating system.
. Set the variable values used in curl example.
+
`CLUSTER_ID=ce559b75-4145-11ee-b51a-005056aee9fb`
. Copy the curl example from the workflow page.
. Paste the example into shell terminal.
. Press *ENTER* which:
.. Substitutes the variable values
.. Executes the curl command
