---
sidebar: sidebar
permalink: rest/create_user_role.html
keywords:
summary:
---

= Create user with a role
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Creating a user with an associated role is a multi-step process.

== Prepare to create a user and role

You should first prepare by reviewing the security requirements and options.

.What ONTAP release are you using?

The ONTAP release affects the REST endpoints and RBAC features available.

.Identify the protected resources and scope

You need to identify the resources to be protected and the scope (cluster or SVM).

.What access should the user have?

After identifying the resources and scope, you should determine the type of access to be granted.

.How will the users access ONTAP?

Will the user access ONTAP primarily through the REST API or CLI?

.Can you use one of the built-in roles or is a custom role needed?

It is more convenient to use an existing built-in role but you can create a new custom role if needed.

.Type of role

xxx
>> REST or traditional

== Create a user with a custom role

The workflow included below illustrates the typical steps needed to custom REST role and associate it with a new user. Both the user and role have an SVM scope and are associated with a specific data SVM.

[NOTE]
The workflow is meant to illustrate the entire end-to-end process. However, several of the steps may be optional and so unnecessary depending on your environment. For example, you can create a user and assign a role in one step rather than the two steps as shown.

=== 1. List the data SVMs in the cluster

Perform the following REST API call to list the data SVMs in the cluster. The UUID and name of each SVM is provided. You need to select the SVM you want to define the user and role to from the list.

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

=== 2. List the users defined to the SVM

Perform the following REST API call to list the users defined for a specific SVM. Based on this you will be able to select a unique name for the new user and avoid duplication.

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

=== 3. List the REST roles defined to the SVM

Perform the following REST API call to list the roles defined for a specific SVM. Based on this you will be able to select a unique name for the new role and avoid duplication.

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

=== 4. Create a custom REST role

Perform the following REST API call to a create a custom REST role. This role xxx

[TIP]
Locate Vijay's email. All operations not explicitly allowed are denied.

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

=== 5. Optionally use the CLI to display the mapped role

xxx
>> mapped traditional

=== 6. Create a user

xxx
>> TIP: Can include role, if not default for SVM is vsadmin which is taken in this example
>> HTTP management protocol

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

=== 7. Add the role to the user

xxx
>> modify

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

=== 8. Sign in to the SVM using new user credentials

xxx

=== 9. Test access to the REST operation

xxx
