---
sidebar: sidebar
permalink: rest/create_user_role.html
keywords:
summary:
---

= Create user with a role
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Creating a user with an associated role is a multi-step process.

== Prepare to create an ONTAP user and role

Before creating role and assigning it to an ONTAP user account, you should first prepare by reviewing the security requirements and options as described below.

.What ONTAP release are you using?

The ONTAP release determines what REST endpoints and RBAC features are available.

.Identify the protected resources and scope

You need to identify the resources or commands to be protected and the scope (cluster or SVM).

.What access should the user have?

After identifying the resources and scope, you need to determine the access level to be granted.

.How will the users access ONTAP?

Will the user access ONTAP through the REST API or CLI? Or both?

.Is one of the built-in roles sufficient or is a custom role needed?

It is more convenient to use an existing built-in role but you can create a new custom role if needed.

.Type of role

Based on the security requirements and ONTAP, should you choose a REST or traditional role?

== Create a user with a custom role

The workflow described below provides one example of creating a role and user. It includes the typical steps needed to create a custom REST role and associate it with a new user. Both the user and role have an SVM scope and are associated with a specific data SVM.

[NOTE]
The workflow is meant to illustrate the entire end-to-end process. However, several of the steps may be optional and unnecessary depending on your environment. For example, you can create a user and assign a role in one API call rather than the two steps as shown.

=== 1. List the data SVMs in the cluster

Perform the following REST API call to list the data SVMs in the cluster. The UUID and name of each SVM is provided. You need to select the SVM where you want to define the user and role from the list.

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

=== 2. List the users defined to the SVM

Perform the following REST API call to list the users defined in a specific SVM. Based on this you will be able to select a unique name for the new user and avoid duplication.

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

=== 3. List the REST roles defined to the SVM

Perform the following REST API call to list the roles defined in a specific SVM. Based on this you will be able to select a unique name for the new role and avoid duplication.

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

=== 4. Create a custom REST role

Perform the following REST API call to a create a custom REST role. This role xxx

[TIP]
Locate Vijay's email. All operations not explicitly allowed are denied.

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

=== 5. Optionally use the CLI to display the mapped role

xxx
>> mapped traditional

=== 6. Create a user

xxx
>> TIP: Can include role, if not default for SVM is vsadmin which is taken in this example
>> HTTP management protocol

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

=== 7. Add the role to the user

xxx
>> modify

>> Review curl sample

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

=== 8. Sign in to the SVM with the new user credentials

xxx
>> Test access to the REST operation
