---
sidebar: sidebar
permalink: rest/rbac_wf_create_user.html
keywords:
summary:
---

= Create user with a role
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use the multi-step workflow described below to create a user with an associated REST role for a data SVM. Before using the workflow, you should review the general process to prepare.

== Prepare to create an ONTAP user with an assigned role

Before creating role and assigning it to an ONTAP user account, you should first prepare by reviewing the security requirements and options as described below.

.What ONTAP release are you using?

The ONTAP release determines what REST endpoints and RBAC features are available.

.Identify the protected resources and scope

You need to identify the resources or commands to be protected and the scope (cluster or SVM).

.What access should the user have?

After identifying the resources and scope, you need to determine the access level to be granted.

.How will the users access ONTAP?

Will the user access ONTAP through the REST API or CLI? Or both?

.Is one of the built-in roles sufficient or is a custom role needed?

It is more convenient to use an existing built-in role but you can create a new custom role if needed.

.What type of role is needed?

Based on the security requirements and ONTAP, you need to choose a REST or traditional role.

== Create a user with a custom role

The workflow described below provides one example for creating a role and user. It includes the typical steps needed to create a custom REST role and associate it with a new user account. Both the user and role have an SVM scope and are associated with a specific data SVM.

[NOTE]
The workflow is meant to illustrate the entire end-to-end process. However, several of the steps may be optional and unnecessary depending on your environment. For example, you can create a user and assign a role in one API call rather than the two steps as shown.

=== 1. List the data SVMs in the cluster

Perform the following REST API call to list the data SVMs in the cluster. The UUID and name of each SVM is provided in the output.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/api/svm/svms
|===
//|/accounts/{account_id}/k8s/v1/managedApps/{managedApp_id}/appSnaps

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms?order_by=name' -u admin:password -k --header 'Accept: */*'

.After you finish

You need to select the SVM where you will define the user and role.

=== 2. List the users defined to the SVM

Perform the following REST API call to list the users defined in the SVM you selected.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/api/security/accounts
|===

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/security/accounts/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'

.After you finish

Based on the users already defined in the SVM, choose a unique name for the new user.

=== 3. List the REST roles defined to the SVM

Perform the following REST API call to list the roles defined in a specific SVM.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/api/security/roles
|===

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/security/roles/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'

.After you finish

Based on the roles already defined in the SVM, choose a unique name for the new role.

=== 4. Create a custom REST role

Perform the following REST API call to a create a custom REST role. The role initially has one privilege defined which establishes the default that all access is denied.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/api/security/roles
|===

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/security/roles' --data @JSONinput -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{
  "name": "dprole1",
  "owner": {
    "name": "dmp",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api", "access": "none"},
  ]
}

=== 5. Optionally display the associated mapped role

xxx
>> mapped traditional

=== 6. Update the role by adding privileges

Perform the following REST API call to modify the role by adding privileges.

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

.After you finish

xxx

=== 7. Create a user

Perform the following REST API call to a create a user account. A role is not specified and so the user is role `vsadmin` by default.

>> management protocol (HTTP)?

[TIP]
You can include the custom role as part of creating the user. In this case, you can skip the next stop.

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

=== 8. Update the user by adding a role

Perform the following REST API call to modify the user by adding the REST role.

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms' -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

.After you finish

You can sign in to the SVM management interface using the credentials for the new user.
