---
sidebar: sidebar
permalink: rest/rbac_wf_create_user.html
keywords:
summary:
---

= Create a user with a role
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use the workflow described below to create a user with an associated REST role. Before reviewing the workflow, you should be familiar with the general preparation steps.

== Prepare to create an ONTAP user with an assigned role

Before creating a role and assigning it to an ONTAP user account, you should first prepare by reviewing the security requirements and options as described below.

.What ONTAP release are you using?

The ONTAP release determines what REST endpoints and RBAC features are available.

.Identify the protected resources and scope

You need to identify the resources or commands to be protected and the scope (cluster or SVM).

.What access should the user have?

After identifying the resources and scope, you need to determine the access level to be granted.

.How will the users access ONTAP?

Will the user access ONTAP through the REST API or CLI? Or both?

.Is one of the built-in roles sufficient or is a custom role needed?

It is more convenient to use an existing built-in role but you can create a new custom role if needed.

.What type of role is needed?

Based on the security requirements and ONTAP, you need to choose a REST or traditional role.

== Create a user with a custom role

The workflow described below provides one example for creating a role and user. It includes the typical steps needed to create a custom REST role and associate it with a new user account. Both the user and role have an SVM scope and are associated with a specific data SVM.

[NOTE]
The workflow is meant to illustrate the complete process. Some of the steps may be optional and unnecessary depending on your environment.

=== 1. List the data SVMs in the cluster

Perform the following REST API call to list the data SVMs in the cluster. The UUID and name of each SVM is provided in the output.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/api/svm/svms
|===

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/svm/svms?order_by=name' -u admin:password -k --header 'Accept: */*'

.After you finish

Select the desired SVM from the list where you will define the user and role.

=== 2. List the users defined to the SVM

Perform the following REST API call to list the users defined in the SVM you selected.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/api/security/accounts
|===

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/security/accounts/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'

.After you finish

Based on the users already defined in the SVM, choose a unique name for the new user.

=== 3. List the REST roles defined to the SVM

Perform the following REST API call to list the roles defined in the SVM you selected.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/api/security/roles
|===

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/security/roles/?owner.name=dmp' -u admin:password -k --header 'Accept: */*'

.After you finish

Based on the roles already defined in the SVM, choose a unique name for the new role.

=== 4. Create a custom REST role

Perform the following REST API call to a create a custom REST role. The role has one privilege which establishes the default access of *none* so that initially all access is denied.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/api/security/roles
|===

.JSON input example
[source,json]
{
  "name": "dprole1",
  "owner": {
    "name": "dmp",
    "uuid": "752d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api", "access": "none"},
  ]
}

.curl example
[source,curl]
curl --location -i --request POST 'https://10.222.81.101/api/security/roles' --data @JSONinput -u admin:password -k --header 'Accept: */*'

.After you finish

Optionally perform step 3 again to display the new role.

=== 5. Update the role by adding more privileges

Perform the following REST API call to modify the role by adding privileges as needed.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/api/security/roles/{owner.uuid}/{name}/privileges
|===

.JSON input example
[source,json]
{
  "path": "/api/storage/volumes", "access": "readonly"}
}

.curl example
[source,curl]
curl --location -i --request GET 'https://10.222.81.101/api/security/roles/752d96be-f17c-11ec-9d19-005056bbad91/dprole1/privileges' --data @JSONinput -u admin:password -k --header 'Accept: */*'

.After you finish

Optionally perform step 3 again to display the new role.

=== 6. Create a user

Perform the following REST API call to a create a user account. The role `dprole1` created above is specified.

[TIP]
You can include the user without an assigned role. In this case, the role `vsadmin` is assigned by default. You can modify the user in the future to assign a different role.

.curl example
[source,curl]
curl --location -i --request POST 'https://10.222.81.101/api/security/accounts' --data @JSONinput -u admin:password -k --header 'Accept: */*'

.JSON input example
[source,json]
{

}

.After you finish

You can sign in to the SVM management interface using the credentials for the new user.
