---
sidebar: sidebar
permalink: rest/work_roles_users.html
keywords:
summary:
---

= Work with roles and users
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
After understanding the basic RBAC capabilities, you can get started working with the ONTAP roles and users.

== Administrative access

You can create and manage the ONTAP roles through the REST API or command line interface. The access details are described below.

=== REST API

There are several endpoints that can be used when working with RBAC roles and user accounts as described below. The first four are used to create and manage the roles. The last two are used to create and manage users.

[TIP]
See the ONTAP online link:../reference/api_reference.html[API reference] documentation for more details.

[cols="35,65"*,options="header"]
|===
|Endpoint
|Description

|`/security/roles`
|This endpoint allows you to create a new REST role. Beginning with ONTAP 9.11.1 you can also create a traditional role. In this case, ONTAP determines the type based on the input parameters. You can also retrieve a list of the defined roles.

|`/security/roles/{owner.UUID}/{name}`
|You can retrieve or delete a specific cluster or SVM scoped role. The UUID value identifies the SVM where the role is defined. The name value is the name of the role.

|`/security/roles/{owner.UUID}/{name}/privileges`
|This endpoint allows you to configure the privileges for a specific role. The built-in roles can be retrieved but not updated. See the API reference documentation for your ONTAP release for more information.

|`/security/roles/{owner.UUID}/{name}/privileges/[path]`
|xxx

|`/security/accounts`
|This endpoint allows you to create a new cluster or SVM scoped user account. Several types of information must be included or subsequently added before the account is operational. You can also retrieve a list of the defined user accounts.

|`/security/accounts/{owner.UUID}/{name}`
|You can retrieve, modify, and delete a specific cluster or SVM scoped user account. The UUID value identifies the SVM where the user is defined. The name value is the name of the account.

|===

=== Command line interface

The relevant ONTAP CLI commands are described below. All commands are accessed at the cluster level through an administrator account.

[cols="30,70"*,options="header"]
|===
|Command
|Description
|`security login`
|This is the directory containing the commands needed to create and manage a user login.
|`security login rest-role`
|This is the directory containing the commands needed to create and manage a REST associated with a user login.
|`security login role`
|This is the directory containing the commands needed to create and manage a REST associated with a user login.
|===

== Role definitions

The REST and traditional roles are defined through a set of attributes.

.Owner and scope

A role can be owned by the ONTAP cluster or a specific data SVM within the cluster. The owner also implicitly determines the scope of the role.

.Unique name

Every role has a unique name within its scope. The names of cluster roles must be unique at the ONTAP cluster level while SVM roles must be unique within the specific SVM.

[NOTE]
Beginning with ONTAP 9.11.1, the name of a new REST role must be unique among the REST roles as well as the traditional roles. This is because creating a REST role results in a new traditional _mapping_ role.

.Set of privileges

Each role contains a set of one or more privileges. Each privilege identifies a specific resource or command and the associated access level.

== Privileges

A role can contain one or more privileges. Each privilege definition is a tuple and establishes the level of access to a specific resource or operation.

=== Resource

The resource is identified as either a REST endpoint or CLI command/command directory path.

.REST endpoint

An API endpoint is used to identify the target resource for a REST role.

.CLI command

A specific CLI command identifies the target for a traditional role. A command directory can also be specified, which then includes all the downstream commands in the ONTAP CLI hierarchy.

=== Access level

The access level defines the type of access the role has to the specific resource or path. The access levels are identified through a set of pre-defined keywords. Three access levels were introduced with ONTAP 9.6. They can be used for both traditional and REST roles. In addition, three new access levels were added with ONTAP 9.11.1. These new access levels can only be used with REST roles.

[NOTE]
The access levels follow the CRUD model. With REST, this is based on the primary HTTP methods (POST, GET, PATCH, DELETE). The corresponding CLI operations generally map to the REST operations (create, show, modify, delete).

[cols="20,50,15,15"*,options="header"]
|===
|Access level
|REST primitive
|Added
|REST role only

|None
|n/a
|9.6
|No

|Readonly
|GET
|9.6
|No

|All
|GET, POST, PATCH, DELETE
|9.6
|No

|Read_create
|GET, POST
|9.11.1
|Yes

|Read_modify
|GET, PATCH
|9.11.1
|Yes

|Read_create_modify
|GET, POST, PATCH
|9.11.1
|Yes

|===

=== Optional query

When creating a traditional role, you can optionally include a *query* value to identify the subset of applicable objects for the command or command directory.

== Summary of the built-in roles

There are several pre-defined roles included with ONTAP that you can use at either the cluster or SVM level.

=== Cluster scoped roles

There are five built-in roles available at the cluster level.

[cols="20,80"*,options="header"]
|===
|Role
|Description

|Admin
|Administrators with this role have unrestricted rights and can do anything on the system. They can configure all cluster-level and SVM-level resources.

|Autosupport
|Special role for the AutoSupport account.

|Backup
|Special role for backup software that backs up the system at the cluster level.

|Readonly
|Administrators with this role can view everything at the cluster level, but they can't make any changes.

|None
|No administrative capabilities.

|===

=== SVM scoped roles

There are *XXX* built-in roles available at the SVM level.

[cols="20,80"*,options="header"]
|===
|Role
|Description

|Vsadmin
|xxx

|===

== Comparing the role types

Before selecting a *REST* role or *traditional* role, you should be aware of the differences. Some of the ways that the roles can be compared are described below.

=== How the user accesses ONTAP

>> required access and suggested role

[cols="2,7"*,options="header"]
|===
|Access
|Suggested type
|REST API only
|REST role
|REST API and CLI
|REST role
|CLI only
|Traditional role
|===

=== Resolution of access path

The defined access path for a REST role is based on a REST endpoint. The defined access path for a traditional role is based on a CLI command or command directory.
